### ISSUE TITLE
Issue in reproducing the funnel methadynamics tutorial

### ISSUE THREAD

**Issue by velocirraptor23** [michellab/biosimspace#428] opened 2023-12-06 15:11 UTC
Hi,

I have been working witht he tutorials, and reproducing them in my system.
Recently I found an issue on the funnel methadynamics tutorial. This happens only in the part were the methadynamics run with OpenMM:

--------------
protocol = BSS.Protocol.Equilibration(runtime=0.01*BSS.Units.Time.nanosecond)
process = BSS.Process.OpenMM(minimised, protocol)
# Start the process in the background.
process.start()
# Wait for the process to finish.
process.wait()
---------------------

*First I got a problem importing ..._utils on the methadynamics.py script

---------------------
Traceback (most recent call last):
  File "/cluster/ddu/cmmartinez001/Projects/openB/fun-metaD-work_dir/openmm_script.py", line 6, in <module>
    from metadynamics import *
  File "/cluster/ddu/cmmartinez001/Projects/openB/fun-metaD-work_dir/metadynamics.py", line 31, in <module>
    from ..._Utils import _try_import
ImportError: attempted relative import with no known parent package
---------------------

*Then instead of calling openMM like that  I changed it for :

---------------------
import openmm as mm
import openmm.unit as unit
---------------------

*Then error I got is this:

---------------------
Traceback (most recent call last):
  File "/cluster/ddu/cmmartinez001/Projects/openB/test/openmm_script.py", line 111, in <module>
    simulation = Simulation(prm.topology,
  File "/cluster/ddu/cmmartinez001/miniconda3/envs/CST/lib/python3.9/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/cluster/ddu/cmmartinez001/miniconda3/envs/CST/lib/python3.9/site-packages/openmm/openmm.py", line 2694, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Two Forces define different default values for the parameter 'k'.
--------------------

*I got those errors even in the example. 

Just wondering if I am doing something wrong. I prepare a folder where I have the inputs and followed the tutorial described.

Biopsimspace version: 2023.5.0.dev+35.g66512f27
Python 3.9

Thanks a lot,

Cesar

**Comment by lohedges** [comment] 2023-12-06 15:29
Thanks for reporting.

I can reproduce the first issue. It looks like someone has incorrectly put a `try_import` block inside our metadynamics helper script. (This is a patched version of the OpenMM metadynamics driver). This means that the code is no longer self-contained and can be run without BioSImSpace.

Just trying to reproduce the second problem.

**Comment by lohedges** [comment] 2023-12-06 15:39
Closing since these are now logged on the OpenBioSim issue tracker [here](https://github.com/OpenBioSim/biosimspace/issues/215) and [here](https://github.com/OpenBioSim/biosimspace/issues/216). Please follow developments on those threads.

**Closed as completed by lohedges** 2023-12-06 15:39 UTC
Labels: bug
