### ISSUE TITLE
Flag which atom breaks the ring 

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#248] opened 2021-11-10 06:44 UTC
**Is your feature request related to a problem? Please describe.**
The default behavior of BSS.Align.matchAtoms() would match the atoms in the methyl to the atoms in the ring in the following example, which would raise an  `IncompatibleError: The merge has opened/closed a ring`. If we want to proceed with the merging, we need to delete the unwanted atom index in the mapping.  
![image](https://user-images.githubusercontent.com/5920217/141060881-3055fdd9-9ad1-473c-b8db-f610b98b28df.png)

Code I used:
```python
import BioSimSpace as BSS
mol1 = BSS.Parameters.gaff('CC1=CC=CC=C1').getMolecule()
mol2 = BSS.Parameters.gaff('C1=CC=C(C=C1)C1=CC=CC=C1').getMolecule()
mapping = BSS.Align.matchAtoms(mol1, mol2)
BSS.Align.merge(mol1, mol2, mapping=mapping)
```

**Describe the solution you'd like**
It would be nice to show the index of the atoms which break the ring in the error information, or we could have a function to check whether there are atoms breaking the ring in the mapping. 

**Describe alternatives you've considered**
We may use `try...except` to loop from all the combinations of the mapping and delete it to get the successful mappings, but it's quite inefficient.

**Comment by lohedges** [comment] 2021-11-10 13:27
I'm not sure it's as simple as this. The mapping simply defines which atoms are _common_ between the two molecules. Atoms that aren't in the mapping still exist in the end states as dummies, so can still be involved in a ring breaking event during the perturbation. The check isn't only applied to atoms in the mapping, rather the _entire_ merged topology. In this sense, it is the topologies of the two constituent molecules and morph that defines whether the merge breaks a ring, not the mapping itself. (This is why the error says "The merge has opened/closed..." rather than "The mapping has opened/closed...".)

**Comment by lohedges** [comment] 2021-11-10 13:43
In this particular case it might be that the ring breaking check is too strict, i.e a new ring has been grown. The check is hard to generalise, but I can think about how to catch this case.

**Comment by kexul** [comment] 2021-11-10 13:57
> Atoms that aren't in the mapping still exist in the end states as dummies, so can still be involved in a ring breaking event during the perturbation. The check isn't only applied to atoms in the mapping, rather the entire merged topology. 

Thanks for the clarification, new lesson learned. 

I'm surprised that the merging still failed after removing index `0, 7, 9` from the mapping, too. Maybe I'm providing a bad example here. In my previous experiments (not including this case), after deleting the index mapped to the ring,  the merge function would proceed with no error. 
![企业微信截图_16365522033232](https://user-images.githubusercontent.com/5920217/141125298-392f5b6d-5231-4b8c-9d58-7763f16b2420.png)

**Comment by lohedges** [comment] 2021-11-10 14:59
In this case the error results from atom index 1 in mol1. However, this is in a ring both before and after the transformation, so I'm not sure why the error has been triggered. I'll try to work out why it thinks it has changed.

**Comment by lohedges** [comment] 2021-11-10 15:03
I see what the issue is. We check that if there is a change in the atom being _in_ a _ring_ or _on_ a ring. In this case, atom index 1 is _in_ a ring in both states, but is also _on_ a ring in one (connected through a single bond). If it is _in_ or _on_ a ring, then we should ignore the break.

**Comment by lohedges** [comment] 2021-11-10 15:13
Related to [this](https://github.com/michellab/BioSimSpace/pull/108) pull request. The fixes implemented there clearly don't catch all edge cases.

**Comment by lohedges** [comment] 2021-11-10 17:12
I've added in some extra checks to prevent ring growth being flagged as ring breaking. The merge should now proceed when you delete 0, 7, and 9 from the mapping. I'll have a think of how to best display the indices of the atoms that are involved in ring breaking, since it isn't super easy in the code as things stand.

Cheers.

**Comment by kexul** [comment] 2021-11-11 02:01
Thanks so much for your work!

**Closed** 2021-11-25 02:32 UTC
