### ISSUE TITLE
Convert molecule to system hangs 

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#293] opened 2022-04-13 13:44 UTC
Dear BioSimSpace developers:
      Recently I'm trying to build a protein mutation system by BioSimSpace, I've managed to merge the proteins. When I try to solvate it with water, the program hangs.
 As far as I can see, it freezes when enumerating the molecules from the system: https://github.com/michellab/BioSimSpace/blob/a2917dce3e76bd69b397aabc30a155156632c046/python/BioSimSpace/_SireWrappers/_system.py#L138-L141

Here is the code I used: 
```python 
import BioSimSpace as BSS
with open('merged.pkl', 'rb') as f:
        merged = pickle.load(f)
sys = BSS.Solvent.tip3p(merged, [10*BSS.Units.Length.nanometer]*3, is_neutral=True)
```
[merged.zip](https://github.com/michellab/BioSimSpace/files/8481875/merged.zip)

Thanks!

**Comment by jmichel80** [comment] 2022-04-13 16:06
which engine do you intend to use for the FEP calculations ? The current version of SOMD may struggle to run a protein perturbation due to file format limitations.

**Comment by kexul** [comment] 2022-04-13 16:59
Thanks for checking!😃 @lohedges 

> which engine do you intend to use for the FEP calculations ? The current version of SOMD may struggle to run a protein perturbation due to file format limitations.

Hi @jmichel80 ,  as you said, the current version of SOMD has some limitations for protein perturbation.  I tried perturbing all of the atoms in the protein, when writing the `.pert` file, there is a four characters limit for residue name, and BioSimSpace tries to add a random suffix, which violates the rule. 
I may try to parametrize the residue separately using GAFF and add it back to the protein, then identify the particular residue to be perturbed with some modification to Sire code, cause the current version treats the protein as a whole. 
As for now, I'd like to build a pipeline using **Gromacs** and reproduce the result in this[ paper](https://pubs.acs.org/doi/10.1021/acs.jcim.1c01243) as a prototype. Then switch to SOMD cause it's much faster. In fact, the merged molecule could be saved to Gromacs format topology without error, at least I can solvate the molecule manually using `gmx`  and run some simulations.

**Comment by lohedges** [comment] 2022-04-13 18:09
It's failing here: https://github.com/michellab/BioSimSpace/blob/a2917dce3e76bd69b397aabc30a155156632c046/python/BioSimSpace/_SireWrappers/_molecule.py#L1576-L1578

This is when we are reconstructing the end states of the merged molecule when extracting a molecule from the system, either by index, or within an iterator using `__getitem__`. The issue is that we are storing a Sire system, then extracting the molecules and converting them to wrapped BioSimSpace objects only when necessary, which involves reconstructing certain attributes. The `extract` method is written in Python, so iterating over the molecule and creating an appropriate partial molecule is slow when the merged system is large, which it is here. (Typically it is only 100 atoms max.) This is something that I'll speed up by writing in the C++ layer (Sire) and creating an appropriate wrapper.

The logic above was actually written pre-pickling and we _don't_ need to extract the end states, since they are included as properties of the pickled object, i.e. `molecule0` and `molecule1`. (The above assumed you would be reconstructing from file.) We can avoid the extraction in the constructor of `BioSimSpace._SireWrappers.Molecule` as follows:

```python
...

        # A Sire Molecule object.
        if isinstance(molecule, _SireMol.Molecule):
            super().__init__(molecule)
            if self._sire_object.hasProperty("is_perturbable"):
                self._convertFromMergedMolecule()
                if molecule.hasProperty("molecule0"):
                    self._molecule = Molecule(molecule.property("molecule0"))
                else:
                    self._molecule0, _ = self._extractMolecule()
                if molecule.hasProperty("molecule1"):
                    self._molecule = Molecule(molecule.property("molecule1"))
                else:
                    self._molecule1, _ = self._extractMolecule(is_lambda1=True)

...
```

I'll try to add this in tomorrow. I've made a few other edits to `devel` today that I need to fully test before pushing. I'll work on faster C++ wrapper when I get time.

Thanks again for reporting!

**Closed** 2022-04-14 13:43 UTC

**Comment by kexul** [comment] 2022-04-17 06:32
Thanks @lohedges , the updated code worked very well.
