### ISSUE TITLE
LOMAP fails with "AlignmentError: Unable to compute MCS of molecules!"

### ISSUE THREAD

**Issue by jasmin-guven** [michellab/BioSimSpace#348] opened 2022-07-01 12:30 UTC
Hi,
I'm trying to create a LOMAP perturbation network for my 16 ligands (prepared in Cresset Flare) 

Here's what I wrote:
```
import BioSimSpace as bss
import glob
ligand_path = "../inputs/ligands/"
ligand_files = glob.glob(ligand_path+"*.mol2")

ligands = []
ligand_names = []
for file in ligand_files:
    ligand_name = file.split("/")[-1].replace(".mol2", "")
    ligand_names.append(ligand_name)

    ligand = bss.IO.readMolecules(file)[0]
    ligands.append(ligand)
    
transformations, lomap_scores = bss.Align.generateNetwork(ligands, plot_network=True, names=ligand_names)
```
And the error:
```
---------------------------------------------------------------------------
AlignmentError                            Traceback (most recent call last)
Input In [9], in <cell line: 14>()
     11     ligand = bss.IO.readMolecules(file)[0]
     12     ligands.append(ligand)
---> 14 transformations, lomap_scores = bss.Align.generateNetwork(ligands, plot_network=True, names=ligand_names)

File ~/Software/miniconda3/envs/bss-d/lib/python3.9/site-packages/BioSimSpace/Align/_align.py:528, in generateNetwork(molecules, names, work_dir, plot_network, links_file, property_map, n_edges_forced)
    526         raise _AlignmentError(msg) from e
    527     else:
--> 528         raise _AlignmentError(msg) from None
    530 # 3) Load all ligands, make 2D depiction aligned to the template and save to file.
    531 try:

AlignmentError: Unable to compute MCS of molecules!
```

## Context

* Operating System: Linux
* Installation method: conda
* System: KPC-2 in compound with ligand 1 (PDB 6D15) + 15 analogs created in Cresset Flare. Attached is a zip file of the `.mol2` files.

@annamherz also had the same problem with some of the TYK2 ligands.

[ligands.zip](https://github.com/michellab/BioSimSpace/files/9028801/ligands.zip)

Thanks so much in advance!

**Comment by lohedges** [comment] 2022-07-01 12:43
Hi there,

By making BioSImSpace output verbose error messages we can get more info on what's going on. In your case, adding:

```
bss.setVerbose(True)
```

This gives:

```
------------------------------
Traceback (most recent call last):
  File "/home/lester/Code/BioSimSpace/python/BioSimSpace/Align/_align.py", line 511, in generateNetwork
    rdmols = [_Chem.RemoveHs(mol) for mol in rdmols]
  File "/home/lester/Code/BioSimSpace/python/BioSimSpace/Align/_align.py", line 511, in <listcomp>
    rdmols = [_Chem.RemoveHs(mol) for mol in rdmols]
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.RemoveHs(NoneType)
did not match C++ signature:
    RemoveHs(RDKit::ROMol mol, RDKit::MolOps::RemoveHsParameters params, bool sanitize=True)
    RemoveHs(RDKit::ROMol mol, bool implicitOnly=False, bool updateExplicitCount=False, bool sanitize=True)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    transformations, lomap_scores = bss.Align.generateNetwork(ligands, plot_network=True, names=ligand_names)
  File "/home/lester/Code/BioSimSpace/python/BioSimSpace/Align/_align.py", line 526, in generateNetwork
    raise _AlignmentError(msg) from e
BioSimSpace._Exceptions._exceptions.AlignmentError: Unable to compute MCS of molecules!: ArgumentError('Python argument types in\n    rdkit.Chem.rdmolops.RemoveHs(NoneType)\ndid not match C++ signature:\n    RemoveHs(RDKit::ROMol mol, RDKit::MolOps::RemoveHsParameters params, bool sanitize=True)\n    RemoveHs(RDKit::ROMol mol, bool implicitOnly=False, bool updateExplicitCount=False, bool sanitize=True)')
```

It looks like something is mismatching with the RDKit API when calling the `RemoveHs` function.  I'll try to figure out what's going on and report back.

**Comment by lohedges** [comment] 2022-07-01 12:49
Printing out the reporting `RDKit` molecules here:

```python
# 2) Find the MCS of the molecules to use as a template.
  try:
    # Remove hydrogens to dramatically speed up MCS algorithm.
    for mol in rdmols:
      print(mol)
```

gives:

```
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
```

It looks like `RDKit is returning `NoneType` for the molecules loaded from file, rather than throwing an exception, which would otherwise be caught. I'll try to figure out why this is. We can always check for this, then report a warning for any molecules that failed to load.

**Comment by lohedges** [comment] 2022-07-01 12:54
Writing your output to a directory using the `work_dir` option, then loading with `RDKit` directly does indeed return a `NoneType`. Annoyingly `RDKit` _prints_ an error, but doesn't throw an exception.

```python
from rdkit import Chem
rdmol = Chem.rdmolfiles.MolFromMol2File("tmp/inputs/000_lig_h_15.mol2")
```

gives:

```
[13:51:19]

****
Post-condition Violation
Element 'ca' not found
Violation occurred on line 93 in file /home/conda/feedstock_root/build_artifacts/rdkit_1654409050232/work/Code/GraphMol/PeriodicTable.h
Failed Expression: anum > -1
****
```

I'll see if formats other than `Mol2` work. If so, we can use that instead, or try multiple formats until one works. I still need to update the code so it uses the new SDF parser, which should be more reliable.

**Comment by jasmin-guven** [comment] 2022-07-01 13:02
Thanks so much for the quick reply Lester!

**Comment by lohedges** [comment] 2022-07-01 13:30
Actually, I had messed up, the PDB wasn't written so the `OSError` was thrown because the file didn't exist. The PDBs do load, but it's returning empty lists for the transformation and scores. Will try the SDFs too.

**Comment by lohedges** [comment] 2022-07-01 13:33
Yes, SDF works! I'll try again with PDB to see what's gone wrong.

I've updated the code so that it always uses SDF if that was the original file format. If not, it writes to Mol2 and PDB and tries both formats. I'll push some changes once I'm happy that it works as expected.

**Comment by lohedges** [comment] 2022-07-01 13:35
Ah, I'm not checking interactively. I'll check that too.

**Comment by lohedges** [comment] 2022-07-01 13:38
It works for me locally.

![generate_network](https://user-images.githubusercontent.com/648557/176905643-f2bacd81-984e-481d-a881-3faa764c8f75.png)

I'll just try to figure out the PDB issue then will push a PR.

Cheers.

**Comment by annamherz** [comment] 2022-07-01 14:04
> Tried sdf on my end, I think the transformations work, but it's just not able to create the network plot:

Hi! sdf files also work for me, but I get the same error message when setting `plot_network=True` of `AlignmentError: Unable to create network plot!: TypeError("argument of type 'float' is not iterable")`.

**Comment by lohedges** [comment] 2022-07-01 14:35
That's strange. It shouldn't work with the Mol2 files, at least that's what I see here. I can only get it to work with the SDF files, with the resulting scores shown in the image above. Do those scores agree with either of yours?

Just to check, are you clearing the LOMAP output file each time? LOMAP will load the format that it finds first, so might not be picking up the new files written by BioSimSpace. (This won't be an issue if you aren't using the `work_dir` option.)

Could you share what scores you are getting for the above inputs?

**Comment by annamherz** [comment] 2022-07-03 13:44
> That's strange. It shouldn't work with the Mol2 files, at least that's what I see here. I can only get it to work with the SDF files, with the resulting scores shown in the image above. Do those scores agree with either of yours?

Ah yes, it must have been because I was using the jupyter notebooks and it had still saved the values from running the sdf files. Running non-interactively with fix_348, it doesn't work with mol2 files, and with sdf files I get the following for @jasmin-guven 's ligands:
```
('lig_5', 'lig_1') 0.90484
('lig_5', 'lig_11') 0.86071
('lig_16', 'lig_13') 0.90484
('lig_16', 'lig_9') 0.90484
('lig_6', 'lig_13') 0.95123
('lig_6', 'lig_9') 0.95123
('lig_15', 'lig_14') 0.90484
('lig_15', 'lig_11') 0.90484
('lig_12', 'lig_3') 0.63763
('lig_12', 'lig_11') 0.90484
('lig_2', 'lig_4') 0.86071
('lig_2', 'lig_9') 0.7788
('lig_1', 'lig_4') 0.90484
('lig_4', 'lig_11') 0.86071
('lig_4', 'lig_9') 0.90484
('lig_8', 'lig_10') 0.95123
('lig_8', 'lig_9') 0.90484
('lig_3', 'lig_11') 0.70469
('lig_10', 'lig_7') 0.86071
('lig_14', 'lig_11') 0.81873
('lig_7', 'lig_9') 0.86071
```
so with the fix all the values are different now.

**Comment by jasmin-guven** [comment] 2022-07-03 15:19
Thanks @annamherz for running these for me! 

I actually got LOMAP to run in a bit of a hacky way (not using `fix_348`), and got the following:
```
ligand_1,ligand_2,LOMAP_score
lig_1,lig_4,0.9048
lig_1,lig_5,0.9048
lig_10,lig_8,0.9512
lig_10,lig_9,0.9512
lig_11,lig_12,0.9048
lig_11,lig_14,0.8187
lig_11,lig_3,0.7047
lig_11,lig_4,0.8607
lig_11,lig_5,0.8607
lig_12,lig_15,0.8187
lig_13,lig_16,0.9048
lig_13,lig_6,0.9512
lig_14,lig_15,0.9048
lig_15,lig_3,0.6376
lig_16,lig_9,0.9048
lig_2,lig_4,0.8607
lig_2,lig_9,0.7788
lig_4,lig_9,0.9048
lig_6,lig_7,0.8607
lig_7,lig_9,0.8607
lig_8,lig_9,0.9048
```

**Comment by lohedges** [comment] 2022-07-03 20:02
This is what I get using the SDF code shown above, where the results are sorted by score:

```python
transformations, lomap_scores = bss.Align.generateNetwork(ligands, plot_network=True, names=ligand_names, work_dir="tmp")

for t, s in sorted(zip(transformations, lomap_scores), key = lambda x:x[1]):
    print(f"({ligand_names[t[0]]}, {ligand_names[t[1]]}), {s}")

(lig_3, lig_15), 0.63763
(lig_3, lig_11), 0.70469
(lig_2, lig_10), 0.7788
(lig_12, lig_15), 0.81873
(lig_14, lig_11), 0.81873
(lig_2, lig_4), 0.86071
(lig_9, lig_7), 0.86071
(lig_4, lig_11), 0.86071
(lig_5, lig_11), 0.86071
(lig_7, lig_10), 0.86071
(lig_8, lig_9), 0.90484
(lig_16, lig_9), 0.90484
(lig_16, lig_13), 0.90484
(lig_1, lig_4), 0.90484
(lig_1, lig_5), 0.90484
(lig_4, lig_10), 0.90484
(lig_12, lig_11), 0.90484
(lig_14, lig_15), 0.90484
(lig_8, lig_10), 0.95123
(lig_6, lig_10), 0.95123
(lig_6, lig_13), 0.95123
(lig_9, lig_10), 0.95123
```

This seems to agree with what you are now seeing.

Can you confirm the outstanding issues...

* You say these results are different to what you were seeing before? Was the previous result that all scores were the same? If so, I can't reproduce this at my end.
* Are you still seeing issues with the network plot in a Jupyter notebook? It is working for me, both on Linux and macOS.

Cheers.

**Comment by jasmin-guven** [comment] 2022-07-03 20:40
Hi Lester, 

* When I use LOMAP from `bss.Align.generateNetwork(ligands, plot_network=False, names=ligand_names)`, the scores I get are all equal to 1.2214, so they are different (and probably wrong) to what we managed to get with the fix.

* Using `plot_network=True` still fails on Jupyter Notebook, I believe @annamherz still also has this issue?

Code:
```
import BioSimSpace as bss
import glob
ligand_path = "../inputs/ligands/lomap/"
ligand_files = glob.glob(ligand_path+"*.sdf")

ligands = []
ligand_names = []
for file in ligand_files:
    ligand_name = file.split("/")[-1].replace(".sdf", "")
    ligand_names.append(ligand_name)
    print(ligand_name)
    ligand = bss.IO.readMolecules(file)[0]
    ligands.append(ligand)

transformations, lomap_scores = bss.Align.generateNetwork(ligands, plot_network=True, names=ligand_names, work_dir="tmp")

for t, s in sorted(zip(transformations, lomap_scores), key = lambda x:x[1]):
    print(f"({ligand_names[t[0]]}, {ligand_names[t[1]]}), {s}")
```
Error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/Software/miniconda3/envs/bss-d/lib/python3.9/site-packages/BioSimSpace/Align/_align.py:587, in generateNetwork(molecules, names, work_dir, plot_network, links_file, property_map, n_edges_forced)
    585 try:
    586     # Convert to a dot graph.
--> 587     dot_graph = _nx.drawing.nx_pydot.to_pydot(graph)
    589     # Write to a PNG.

File ~/Software/miniconda3/envs/bss-d/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py:302, in to_pydot(N)
    297 u, v = str(u), str(v)
    298 raise_error = (
    299     _check_colon_quotes(u)
    300     or _check_colon_quotes(v)
    301     or (
--> 302         any(
    303             (_check_colon_quotes(k) or _check_colon_quotes(v))
    304             for k, v in edgedata.items()
    305         )
    306     )
    307 )
    308 if raise_error:

File ~/Software/miniconda3/envs/bss-d/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py:303, in <genexpr>(.0)
    297 u, v = str(u), str(v)
    298 raise_error = (
    299     _check_colon_quotes(u)
    300     or _check_colon_quotes(v)
    301     or (
    302         any(
--> 303             (_check_colon_quotes(k) or _check_colon_quotes(v))
    304             for k, v in edgedata.items()
    305         )
    306     )
    307 )
    308 if raise_error:

File ~/Software/miniconda3/envs/bss-d/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py:199, in _check_colon_quotes(s)
    195 def _check_colon_quotes(s):
    196     # A quick helper function to check if a string has a colon in it
    197     # and if it is quoted properly with double quotes.
    198     # refer https://github.com/pydot/pydot/issues/258
--> 199     return ":" in s and (s[0] != '"' or s[-1] != '"')

TypeError: argument of type 'float' is not iterable

The above exception was the direct cause of the following exception:

AlignmentError                            Traceback (most recent call last)
Input In [6], in <cell line: 16>()
     13     ligand = bss.IO.readMolecules(file)[0]
     14     ligands.append(ligand)
---> 16 transformations, lomap_scores = bss.Align.generateNetwork(ligands, plot_network=True, names=ligand_names, work_dir="tmp")
     18 for t, s in sorted(zip(transformations, lomap_scores), key = lambda x:x[1]):
     19     print(f"({ligand_names[t[0]]}, {ligand_names[t[1]]}), {s}")

File ~/Software/miniconda3/envs/bss-d/lib/python3.9/site-packages/BioSimSpace/Align/_align.py:604, in generateNetwork(molecules, names, work_dir, plot_network, links_file, property_map, n_edges_forced)
    602 if _isVerbose():
    603     msg += ": " + getattr(e, "message", repr(e))
--> 604     raise _AlignmentError(msg) from e
    605 else:
    606     raise _AlignmentError(msg) from None

AlignmentError: Unable to create network plot!: TypeError("argument of type 'float' is not iterable")
```



Thanks so much.

**Comment by lohedges** [comment] 2022-07-03 21:18
Could you confirm what OS you are using?

**Comment by jasmin-guven** [comment] 2022-07-03 21:31
Running on Linux.

**Comment by lohedges** [comment] 2022-07-03 21:40
I can confirm that I see the same thing with Python 3.9 on Linux. (Not with 3.7, which was my development environment.) I'll try to figure out what's gone wrong. We may need to pin the version of `networkx` or `pydot`.

**Comment by jasmin-guven** [comment] 2022-07-03 21:43
I see! Yep I am using python 3.9. Thanks so much for your help Lester!

**Comment by annamherz** [comment] 2022-07-03 22:17
> * Using `plot_network=True` still fails on Jupyter Notebook, I believe @annamherz still also has this issue?

Yep! I'm also running linux and python 3.9.

**Comment by lohedges** [comment] 2022-07-04 08:35
The issue is `networkx`. WIth Python 3.9 I have the following installed:

```
conda list networkx
# packages in environment at /home/lester/.conda/envs/biosimspace-dev:
#
# Name                    Version                   Build  Channel
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
```

In my Sire dev environment, which is Python 3.7, I have:

```
~/sire.app/bin/conda list networkx
# packages in environment at /home/lester/sire.app:
#
# Name                    Version                   Build  Channel
networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
```

(In both cases, the version of `pydot` is the same.)

Downgrading the 3.9 environment to `networkx` 3.7 works:

```
conda install networkx=2.7
```

For now I'll pin `networkx` to versions less than 2.8, then report the issue to see if they can fix it.

**Comment by lohedges** [comment] 2022-07-04 08:50
Actually, it can be fixed in BioSimSpace with the following:

```
diff --git a/python/BioSimSpace/Align/_align.py b/python/BioSimSpace/Align/_align.py
index 6e314afc..695182bd 100644
--- a/python/BioSimSpace/Align/_align.py
+++ b/python/BioSimSpace/Align/_align.py
@@ -606,7 +606,7 @@ def generateNetwork(molecules, names=None, work_dir=None, plot_network=False,
             # Create a dictionary mapping the edges to their scores.
             edge_dict = {}
             for x, (node0, node1) in enumerate(edges):
-                edge_dict[(names[node0], names[node1])] = round(scores[x], 2)
+                edge_dict[(names[node0], names[node1])] = str(round(scores[x], 2))
```

Previously it was possible to have a `float` type label, whereas now it is assumed that is a `str`, since they iterate over it. It would be useful if `networkx` actually had some type/value checking when creating the graph, as this would avoid issues like this.

**Closed** 2022-07-04 08:53 UTC
Labels: bug

**Comment by jasmin-guven** [comment] 2022-07-04 08:54
Amazing thanks so much! Can’t believe they don’t do type checks! Anyway I’m glad it’s not a complicated issue. 

Many thanks again,

Jasmin

**Comment by lohedges** [comment] 2022-07-04 08:56
No problem. Thanks for reporting, and let me know if you come across other issues. This isn't a very well tested part of the code so there may well be other edge cases. (It was added quickly for a workshop.)

**Comment by annamherz** [comment] 2022-07-04 09:55
Thank you :smile:
