### ISSUE TITLE
Mappings for perturbations involving fused rings

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#73] opened 2019-03-28 12:33 UTC
I have used 

> https://github.com/michellab/BioSimSpace/tree/devel/nodes/playgroundprepareFEP.ipynb 

to create SOMD input files from the following pair of molecules

> 31vac.parm7 , 31vac.rst7
> 32vac.parm7, 32vac.rst7

The perturbation 31-->32 involves growing a pyridine ring from a benzene ring 

With default settings prepareFEP produces an unexpected mapping where atom H38 in ligand31 has been mapped to atom H31 in ligand32. This stills produces what looks like a legitimate merged molecule because of symmetry, but the expectation was that the RMSDalign option would pick a mapping where atom H36 in ligand 31 is paired with atom H31 in ligand 32.  

The atom names in the merged molecule have changed so it's a bit confusing but we basically end up with a merged molecule that looks like this

![image](https://user-images.githubusercontent.com/11722212/55154297-5829a780-514c-11e9-9259-cbb3e0d6a08e.png)

Where H37 and H38 are initially hydrogen atoms, and become dummy atoms. 

A more efficient mapping could be generated by mapping H37 to N34 and H38 to C37. 
This would avoid overlapping in space atoms that are disappearing with atoms that are appearing during the perturbation. 

However it isn't possible to obtain this mapping by passing this prematch requirement as attempts to set prematch to the relevant atom incides in lig32 and lig31

> prematch= 33-36,36,37

causes BSS.Align.matchAtoms to fail with the following error message

 `AlignmentError: Failed to align molecules when scoring based on mapping: {AtomIdx(36): AtomIdx(37), AtomIdx(33): AtomIdx(36)}`

I tried to bypass the align stage by editing the mapping produced without pre-match requirements to force H37 to map to N34 and H37 to map to C37 but this causes BSS.Align.merge to fail with the following error

`IncompatibleError: Merge has changed the molecular connectivity! Check your atom mapping.
`

The input files are attached.

[31to32.zip](https://github.com/michellab/BioSimSpace/files/3017756/31to32.zip)

Note the desired mapping breaks the strict rule of not breaking rings. However in some instances this may be reasonable see for instance Fig1 in https://link.springer.com/article/10.1007%2Fs10822-013-9678-y 

@lohedges could you please clarify 

- 1) why the mapping between the phenyl hydrogens in 31 and the fused phenylpyridine in 32 are not with the spatially closest equivalent hydrogen despite use of RMSDalign 

- 2) whether it is possible to modify BSS.Align.matchAtoms and BSS.Align.merge to support fusing the two hydrogens in 31 with the nitrogen/carbon in 32. This could be controlled with a flag that controls whether ring breaking is allowed or this use case is likely only valid for fused planar rings.

**Comment by lohedges** [comment] 2019-03-28 14:45
Interesting, I'll look into this. Some quick thoughts:

1) If I add a prematch for your desired hydrogen mapping then what I get back from findMCSmatches is just the prematch, i.e. the MCS matching code in Sire didn't actually find a match. This means the problem is in the MCS matching code, not the scoring in BioSimSpace. I don't know whether this is something to do with the order in which the search is performed.

2) I guess that this would be possible. At the moment the merge function has some checks to ensure that the connectivity of the lambda=0 and lambda=1 states are equivalent. We could disable these if the user wishes to break rings. However, it seems like we can't actually align the molecules based on such mappings so I'll also have to work out what is going wrong with the Sire alignment code.

**Comment by lohedges** [comment] 2019-06-10 15:02
With the new RDKit MCS match we now get a correct mapping for one of the atom pairs:

```
AtomIdx(36) Atom( H37 : 37 ) --> AtomIdx(33) Atom( N34 : 34 )
```

For the other atom that you want to map (H38 to C37), we instead get the following mappings:

```
AtomIdx(37) Atom( H38 : 38 ) --> AtomIdx(30) Atom( H31 : 31 )
AtomIdx(35) Atom( H36 : 36 ) --> AtomIdx(36) Atom( C37 : 37 )
```
Is the mapping between H36 and C37 topologically equivalent to the one you desire? If I add any pre-match involving H38 and C37, then the mapping fails and I simply get the pre-match, e.g.:

```python
import BioSimSpace as BSS
m0 = BSS.IO.readMolecules(BSS.IO.glob("31*")).getMolecules()[0]
m1 = BSS.IO.readMolecules(BSS.IO.glob("32*")).getMolecules()[0]
mapping = BSS.Align.matchAtoms(m0, m1, prematch={AtomIdx(36) : AtomIdx(33), AtomIdx(37) : AtomIdx(36)})
print(mapping)
{AtomIdx(36): AtomIdx(33), AtomIdx(37): AtomIdx(36)}
```

I also need to set `allow_ring_breaking=True` to be able to merge the molecules based on the RDKit mapping.

**Comment by lohedges** [comment] 2019-07-31 13:30
This is now fixed after the recent RDKit scoring function updates.

```python
import BioSimSpace as BSS
from Sire.Mol import AtomIdx

m0 = BSS.IO.readMolecules(BSS.IO.glob("31*")).getMolecules()[0]
m1 = BSS.IO.readMolecules(BSS.IO.glob("32*")).getMolecules()[0]

mapping = BSS.Align.matchAtoms(m0, m1, prematch={36 : 33, 37 : 36})

print(mapping)
{1: 1,
 0: 2,
 2: 0,
 3: 3,
 10: 10,
 9: 9,
 8: 8,
 7: 7,
 6: 6,
 5: 5,
 4: 4,
 33: 41,
 34: 42,
 21: 18,
 22: 19,
 23: 20,
 24: 21,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 20: 17,
 19: 16,
 18: 32,
 17: 31,
 16: 29,
 31: 40,
 37: 36,
 36: 33,
 35: 30,
 32: 28,
 29: 27,
 30: 26,
 27: 25,
 28: 24,
 25: 22,
 26: 23}

for idx0, idx1 in mapping.items():
    print(m0._sire_object.atom(AtomIdx(idx0)), m1._sire_object.atom(AtomIdx(idx1)))
Atom( C2 : 2 ) Atom( C2 : 2 )
Atom( O1 : 1 ) Atom( O3 : 3 )
Atom( O3 : 3 ) Atom( O1 : 1 )
Atom( C4 : 4 ) Atom( C4 : 4 )
Atom( C11 : 11 ) Atom( C11 : 11 )
Atom( C10 : 10 ) Atom( C10 : 10 )
Atom( C9 : 9 ) Atom( C9 : 9 )
Atom( C8 : 8 ) Atom( C8 : 8 )
Atom( C7 : 7 ) Atom( C7 : 7 )
Atom( C6 : 6 ) Atom( C6 : 6 )
Atom( C5 : 5 ) Atom( C5 : 5 )
Atom( N34 : 34 ) Atom( N42 : 42 )
Atom( H35 : 35 ) Atom( H43 : 43 )
Atom( H22 : 22 ) Atom( H19 : 19 )
Atom( H23 : 23 ) Atom( H20 : 20 )
Atom( H24 : 24 ) Atom( H21 : 21 )
Atom( H25 : 25 ) Atom( H22 : 22 )
Atom( C12 : 12 ) Atom( C12 : 12 )
Atom( C13 : 13 ) Atom( C13 : 13 )
Atom( C14 : 14 ) Atom( C14 : 14 )
Atom( O15 : 15 ) Atom( O15 : 15 )
Atom( C16 : 16 ) Atom( C16 : 16 )
Atom( C21 : 21 ) Atom( C18 : 18 )
Atom( C20 : 20 ) Atom( C17 : 17 )
Atom( C19 : 19 ) Atom( C33 : 33 )
Atom( C18 : 18 ) Atom( C32 : 32 )
Atom( C17 : 17 ) Atom( C30 : 30 )
Atom( H32 : 32 ) Atom( H41 : 41 )
Atom( H38 : 38 ) Atom( C37 : 37 )
Atom( H37 : 37 ) Atom( N34 : 34 )
Atom( H36 : 36 ) Atom( H31 : 31 )
Atom( H33 : 33 ) Atom( H29 : 29 )
Atom( H30 : 30 ) Atom( H28 : 28 )
Atom( H31 : 31 ) Atom( H27 : 27 )
Atom( H28 : 28 ) Atom( H26 : 26 )
Atom( H29 : 29 ) Atom( H25 : 25 )
Atom( H26 : 26 ) Atom( H23 : 23 )
Atom( H27 : 27 ) Atom( H24 : 24 )
```

**Closed by lohedges** 2019-07-31 13:30 UTC
Labels: enhancement, question
