### ISSUE TITLE
Gromacs

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#19] opened 2018-05-17 09:24 UTC
This thread is for discussing issues regarding ruinning Gromacs simulations with BioSimSpace.

At present, I'm having significant issues getting even basic simulations, e.g. steepest descent minimisation, to run using BioSimSpace. As a test case, I've been using the simple solvated Kigaki system described in [this](http://www.strodel.info/index_files/lecture/html/tutorial.html) tutorial. I have added example [top](https://github.com/michellab/BioSimSpace/blob/feature-process-gromacs/demo/gromacs/kigaki/kigaki.top) and [gro](https://github.com/michellab/BioSimSpace/blob/feature-process-gromacs/demo/gromacs/kigaki/kigaki.gro) files to the repository.

Major issues include:

* Defining `nrexcl` for different groups, e.g. `nrexcl = 2` means to exclude non-bonded interactions up to two bonds away (I think). This is not preserved in a topology file written by Sire and seems to be hard to calculate for systems converted to the Gromacs format, e.g. originally in Amber format. In my experiences, incorrect values of `nrexcl` make the simulation entirely unstable, i.e. positive potential energies (the system blows up).

* Gromacs mixes topology and configuration information. For example, in solvated simulations, information related to the configuration of the constraint algorithm is included in the water force-field file. Also, a directive in an mdp configuration file could be used to modify parts of an existing topology.

* Solvated simulations aren't working properly since we don't currently support the `exclusions` tag, or deal with constraints (see above). For example, the following part of the Tip3P itp file is needed for a stable simulation.

```c
#ifndef FLEXIBLE

[ settles ]
; OW    funct   doh dhh
1       1       0.09572 0.15139

[ exclusions ]
1   2   3
2   1   3
3   1   2

#else
```

**Comment by eric-jm-lang** [comment] 2018-06-22 23:07
Regarding `nrexcl`, you are correct regarding the meaning. 
From the manual:
> nrexcl = 3 stands for excluding non-bonded interactions between atoms that are no further than 3 bonds away

A value of `nrexcl=3` seems to be the default in Parmed for every type of molecule (see for example [ParmEd/parmed/parameters.py](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py)) and it looks like it is indeed what is the default for small molecules and proteins. 

Examples from the manual seem to suggest that for water it is possible to have `nrexcl=1` which makes sense given the definition. It seems also logical to have `nrexcl=0` in the case of monoatomic ions.

**Comment by chryswoods** [comment] 2018-06-23 14:00
I've added a fix for this in the parser branch in Sire and issued a pull request to bring into devel (parser #211).

**Comment by chryswoods** [comment] 2018-06-25 16:03
I've added a test to SireUnitTests that compares the energies of molecules loaded to and from Eric's files (the amber files and their equivalent from parmed). The test is SireIO/test_ambgro.py. It gives interesting results which show disagreement between the energies of the amber files, our gromacs files and also the parmed gromacs files. Interestingly, converting back from our gromacs to amber gives the same energy, and converting back from parmed gromacs to amber gives the same energy. 

The results of this test are printed below. For each energy term there are five values:

1. The energy from the original amber input files
2. The energy from the gromacs files written by Sire (converted from the amber files)
3. The energy from the gromacs files written by parmed (converted from the amber files by Eric)
4. The energy from the amber files converted from the gromacs files written by Sire
5. The energy from the amber files converted from the gromacs files written by parmed

Ideally, all 5 energies should be identical. This is not the case.

Strangely, the parmed energies don't agree with the amber energies...
The Sire energies agree better, but are also out for some (especially coulomb and bond)

The back-converted amber energies are equal, so 2 == 4 and 3 == 5. Strange.

```
E_{cljff}^{CLJ_{default}}:  -74306.9958019629  -74307.18291528475  -74310.60385158383  -74307.18291528488  -74310.60385158383
E_{cljff}^{LJ_{default}}:  7349.263053051327  7349.039465757929  7352.289416002735  7349.039465757929  7352.2894160027345
E_{cljff}^{coulomb_{default}}:  -81656.25885501422  -81656.22238104268  -81662.89326758657  -81656.22238104281  -81662.89326758657
E_{intraclj}^{CLJ_{default}}:  -8846.926930404212  -1949818.138133785  -1949655.3796204112  -1949818.138133785  -1949655.3796204112
E_{intraclj}^{LJ_{default}}:  -916.1663721393626  -916.1745560819411  -914.8952690047718  -916.1745560819411  -914.8952690047719
E_{intraclj}^{coulomb_{default}}:  -7930.760558264848  -1948901.963577703  -1948740.4843514063  -1948901.963577703  -1948740.4843514063
E_{intraff}^{1-4[LJ]}:  972.1638654037595  972.162691737714  972.881505919929  972.1626909930478  972.8815064894559
E_{intraff}^{1-4[coulomb]}:  13803.918022937934  13803.918301064346  13804.323984910621  13803.918305721187  13804.323989568602
E_{intraff}^{1-4}:  14776.081888341694  14776.08099280206  14777.20549083055  14776.080996714234  14777.205496058057
E_{intraff}^{angle}:  231.70027096935198  231.70031094668428  240.10804588737886  231.70031031666485  240.10804706364388
E_{intraff}^{bend-bend}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{bond}:  106.8991145741713  67.6768473486908  87.93402512045354  67.6768473470172  87.93402512045421
E_{intraff}^{dihedral}:  2282.1984914864333  2282.1976724906235  2282.797793809015  2282.1976701332396  2282.797794328362
E_{intraff}^{improper}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{internal}:  17396.87976537165  17357.65582358806  17388.0453556474  17357.655824511156  17388.04536257052
E_{intraff}^{stretch-bend-torsion}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{stretch-bend}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{stretch-stretch}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{urey_bradley}:  0.0  0.0  0.0  0.0  0.0
E_{total}:  -65757.04296699546  -2006767.6652254816  -2006577.9381163477  -2006767.6652245587  -2006577.9381094244
```

**Comment by chryswoods** [comment] 2018-06-25 17:06
I have now fixed this. The issue is that my test was calculating the intramolecular energy of solvent (water) molecules, which was not zero for the gromacs files (both from Sire and parmed). Removing the intramolecular energy from the solvent molecules gives agreement between Amber and the Sire-produced gromacs files. There is still disagreement with the parmed-produced gromacs files. Given that the Amber files are the source of truth, I think that Sire is right and parmed is wrong...

```
E_{cljff}^{CLJ_{default}}:  -74306.995801963  -74307.18291528491  -74310.60385158377  -74307.18291528473  -74310.6038515838
E_{cljff}^{LJ_{default}}:  7349.263053051328  7349.039465757929  7352.289416002734  7349.039465757929  7352.289416002736
E_{cljff}^{coulomb_{default}}:  -81656.25885501433  -81656.22238104284  -81662.8932675865  -81656.22238104267  -81662.89326758654
E_{intraclj}^{CLJ_{default}}:  -8846.926930404212  -8846.934007427151  -8846.41453633516  -8846.934007427151  -8846.41453633516
E_{intraclj}^{LJ_{default}}:  -916.1663721393626  -916.1745560819411  -914.8952690047718  -916.1745560819411  -914.8952690047718
E_{intraclj}^{coulomb_{default}}:  -7930.760558264848  -7930.7594513452095  -7931.519267330388  -7930.7594513452095  -7931.519267330388
E_{intraff}^{1-4[LJ]}:  972.1638654037595  972.1626917377141  972.881505919929  972.1626909930478  972.8815064894559
E_{intraff}^{1-4[coulomb]}:  13803.918022937934  13803.918301064346  13804.323984910623  13803.918305721187  13804.323989568602
E_{intraff}^{1-4}:  14776.081888341694  14776.08099280206  14777.205490830553  14776.080996714234  14777.205496058057
E_{intraff}^{angle}:  231.70027096935206  231.70031094668443  240.10804588737864  231.7003103166649  240.10804706364408
E_{intraff}^{bend-bend}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{bond}:  67.67795199698396  67.67684734869087  87.93402512045357  67.67684734701722  87.93402512045417
E_{intraff}^{dihedral}:  2282.1984914864324  2282.197672490623  2282.7977938090135  2282.1976701332414  2282.7977943283654
E_{intraff}^{improper}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{internal}:  17357.65860279446  17357.65582358806  17388.0453556474  17357.65582451116  17388.04536257052
E_{intraff}^{stretch-bend-torsion}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{stretch-bend}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{stretch-stretch}:  0.0  0.0  0.0  0.0  0.0
E_{intraff}^{urey_bradley}:  0.0  0.0  0.0  0.0  0.0
E_{total}:  -65796.26412957275  -65796.461099124  -65768.97303227153  -65796.46109820073  -65768.97302534844
```

(I've updated the test so that now it passes - it does not include a fail if the parmed files disagree)

**Closed** 2018-12-21 11:54 UTC
