### ISSUE TITLE
combine.py protein- ligand clash  

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/BioSimSpace#70] opened 2019-03-18 17:11 UTC
I am using combine.py to combine a ligand (orange representation) and a protein but there is a clash between them at the output system resulting in errors during solvation and equilibration. Any ideas how to fix that? 
![Screenshot from 2019-03-18 17-06-35](https://user-images.githubusercontent.com/44237397/54548872-c1692800-49a0-11e9-8931-35f31f70e7b7.png)

**Comment by jmichel80** [comment] 2019-03-18 17:25
Hi @SofiaBariami 

Can you upload the input to the script, and write how you executed the script so we can reproduce your error. 

Best wishes,

Julien

**Comment by lohedges** [comment] 2019-03-18 17:25
I assume that you are using [this](https://github.com/michellab/BioSimSpace/blob/devel/nodes/playground/combine.py) script? There is nothing fancy going on, it just loads two individual systems from file, then creates a composite system by adding them together. If atoms in either of the individual systems have overlapping coordinates, then they will overlap in the composite system. BioSimSpace does not check this. (Not sure if this is something that we want to support? Sire doesn't complain either.)

To fix this, you could either:

1) Make sure the coordinates of the ligand and protein aren't overlapping in the original files.
2) Translate one of the systems so that the protein and ligand don't overlap before combining, e.g.

```python
system1 = BSS.IO.readMolecules(node.getInput("system1"))
system2 = BSS.IO.readMolecules(node.getInput("system2"))
# Translate system1 by 1 Angstrom in the x direction.
system1.translate([BSS.Units.Length.angstrom, 0*BSS.Units.Length.angstrom, 0*BSS.Units.Length.Angstrom)]
combined = system1 + system2
```

**Comment by SofiaBariami** [comment] 2019-03-18 18:04
Thank both of you! 
@jmichel80 thr problem is with [protein-gas](https://github.com/SofiaBariami/qube_project/blob/master/protein-gas.pdb) and [ligand14](https://github.com/SofiaBariami/qube_project/blob/master/14d.pdb) at Leucine 6. The command I used is `combine.py --system1 14d.prm7 14d.rst7 --system2 protein-gas.prm7 protein-gas.rst7 --output prot-lig 
`following [this protocol](https://github.com/michellab/qube-somd/blob/master/amber-gaff/01-setup/README.md). The rst7 and prm7 files can be found [here](https://github.com/SofiaBariami/qube_project).
The output in pdb, rst7 prm7 format  is [here](https://github.com/SofiaBariami/qube_project) with the name prot-lig14.

**Comment by lohedges** [comment] 2019-03-18 18:18
Thanks, I'll take a look tomorrow. Another possibility is that you might
simply need to run a short minimisation in order to fix any bad contacts
before performing the solvation/equilibration.

**Comment by jmichel80** [comment] 2019-03-18 20:56
Hi @SofiaBariami there is nothing wrong with the script, the problem is with the input coordinates of protein-model.pdb. The pdb file was created by converting the pdb provided by Lauren to add missing hydrogen atoms, but this has resulted in a change of coordinates. The ligand pdb coordinates are not aligned anyway with either protein pdb files. 
We need to get from Lauren a protein pdb file that has all hydrogen atoms, and is aligned with the ligands pdb files.

**Comment by jmichel80** [comment] 2019-03-18 21:01
Also you have admin rights to https://github.com/michellab/qube-somd, you can upload all your inputs here rather than https://github.com/SofiaBariami/qube_project

**Comment by lohedges** [comment] 2019-03-19 13:08
Closing since this was an issue with the input files. If we want to discuss support for detecting clashing atom coordinates then we can open another thread.

**Closed by lohedges** 2019-03-19 13:08 UTC
