### ISSUE TITLE
Mapping/merging errors

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#99] opened 2019-07-31 14:29 UTC
BSS seems to have issues with growing/breaking three membered rings, as the ligand pair here (13a_17g):

![13a_17g](https://user-images.githubusercontent.com/50554130/62219869-fb165a80-b3a6-11e9-8c2a-793fdc337385.png)

fail to merge, giving this error:
```
Traceback (most recent call last):
  File "prepareFEP.py", line 185, in <module>
    merged = BSS.Align.merge(lig1, lig2, mapping, allow_ring_breaking=node.getInput("allow_ring_breaking"))
  File "/home/e620070/anaconda3/envs/test_BSS/lib/python3.7/site-packages/BioSimSpace/Align/_align.py", line 576, in merge
    property_map0=property_map0, property_map1=property_map1)
  File "/home/e620070/anaconda3/envs/test_BSS/lib/python3.7/site-packages/BioSimSpace/_SireWrappers/_molecule.py", line 2443, in _merge
    raise _IncompatibleError("Inconsistent number of bonds in merged molecule!")
BioSimSpace._Exceptions._exceptions.IncompatibleError: Inconsistent number of bonds in merged molecule!
 ```
There are more error from this particular testset, but lets tackle them one at a time. [Here](https://github.com/michellab/BioSimSpace/files/3452308/Bace_mapping_tests.zip)
 is the folder with structures, mappings and a notebook. In this particular case I used prepareFEP, with --allow_ring_breaking. BSS version 2019.1.0+228.gd744721

**Comment by lohedges** [comment] 2019-07-31 14:55
Thanks, I'll have a look at our ring opening/closing detection code to see what's going wrong.

**Comment by lohedges** [comment] 2019-07-31 15:11
I see the problem. At present, when the connectivity between atoms changes, I'm testing whether both atoms are part of a ring in one state, and at least one isn't in the other. Looking at atoms 39 and 20 above, the change goes from one being in the ring (2) and one being _on_ the ring (39), to both not being in the ring. I need to add a check for an atom being _on_ a ring as well as _in_ a ring.

**Comment by lohedges** [comment] 2019-07-31 16:31
Could you elaborate on what you mean by:

> 3-mem ring issue, mostly

I've made some tweaks to handle the case above and can now merge the ligand pair successfully. However, others in your input set still don't work:

```
CAT-13c CAT-17i
CAT-13d CAT-13f
CAT-13d CAT-13i
CAT-13e CAT-17g
CAT-13e CAT-17i
CAT-13g CAT-17g
CAT-13g CAT-17i
CAT-13h CAT-17i
CAT-13o CAT-17i
CAT-13o CAT-17h
CAT-17g CAT-13i
CAT-17i CAT-13f
CAT-24 CAT-17e
CAT-24 CAT-17i
CAT-4m CAT-4c
```

I'll work through these to see what other edge cases I'm missing.

**Comment by lohedges** [comment] 2019-07-31 16:33
I also note that some of these don't have the largest mappings.

**Comment by lohedges** [comment] 2019-07-31 16:39
In the first case that I've tested it looks like the connectivity changes, but all atoms remain in a ring. I'll try to figure out what perturbation this relates to.

**Comment by lohedges** [comment] 2019-07-31 17:23
Yes, that looks like the case. I now handle connectivity changes that result from changes in ring size. Here atoms can remain in or on a ring in both end states. This fixes all your problems and all ligand pairs are able to merge. I'll test things thoroughly tomorrow morning and push a new commit.

**Comment by dlukauskis** [comment] 2019-08-01 07:29
Awesome, keep me updated and I can test them to see if they produce similar free energies to other benchmarks.

**Comment by maxkuhn** [comment] 2019-08-01 07:31
Brief comment, as I have worked with this dataset as well: It looks like you are trying to map ligands with different ring sizes (i.e. 13e <=> 17g  cyclobutyl<=> cyclopropyl), which will not work using BioSimSpace. The way to go is to create an intermediate ligand yourself, e.g. set up the perturbations like this: cyclobutyl <=> hydrogen <=> cyclopropyl

**Comment by lohedges** [comment] 2019-08-01 08:07
Thanks, @maxkuhn. I've now updated the ring detection code to catch cases where the rings have different sizes, so BioSimSpace _should_ be able to merge between them successfully. Whether this generates decent results is another matter, so it could be interesting to see if the intermediate is the better choice of pathway. If so, then I will only allow ring changes with another keyword. Do you have any thoughts on this?

**Comment by dlukauskis** [comment] 2019-08-01 08:10
Lets make this optional for now, if the results are as good as with an intermediate, then we can make it default.

**Comment by maxkuhn** [comment] 2019-08-01 09:24
@lohedges I have not tried it myself, but I expect the simulations to crash when enforcing a perturbation between two differently sized rings (at least using SOMD).

**Comment by lohedges** [comment] 2019-08-01 16:15
I've now added support for handling three-membered rings, and for perturbations that change the size of rings, which requires the `allow_ring_size_change=True` option. I've updated `prepareFEP.py` accordingly, and the SOMD pertfile and GROMACS topology writers can handle perturbations where the end states have a different number of bonds.

Note that ring size changes may lead to unstable perturbations, so is disabled by default. I just thought it was good to add the functionality in case different FEP engines can handle it. Let me know if you come across other edge cases that we are missing.

> Awesome, keep me updated and I can test them to see if they produce similar free energies to other benchmarks.

With regards to comparisons to other benchmarks. If you have existing data, please also compare the mappings as well as the free energies. When there are differences, it would be good to document differences in the inputs and protocols between the various methods.

**Comment by dlukauskis** [comment] 2019-08-02 09:42
Great work, Lester! All pairs have merged fine. I've manually checked the mappings and about half of the problem pairs had poor mappings, probably due to symmetries of the pairs. [Here](https://github.com/michellab/BioSimSpace/files/3460609/new_Bace_mapping_tests.zip) is the updated folder with the findings. Check the new pymol session and the notebook.

Is this type of issue possible to tackle in an automated way, or sometimes the user will simply have to prematch for some of the ligand pairs?

**Comment by lohedges** [comment] 2019-08-02 10:00
Thanks for the update, I'll take a look this afternoon.

> Is this type of issue possible to tackle in an automated way, or sometimes the user will simply have to prematch for some of the ligand pairs?

At the moment we've switched to using RDKit for the MCS mapping. It is much faster than our internal code, and seemed to be more reliable too, but it makes it a bit harder to debug/fix when things go wrong. If you find that you are experiencing mapping issues for particular ligand pairs definitely keep track of them and log them in an issue here, like you are doing. (It's really useful that people are using BioSimSpace to set up FEP input for a wide range of systems in order to catch edge cases.) If we can detect common features that are likely to lead to poor mappings, then we could warn the user, or apply our own pre-matching rules in attempt to fix the problems.

I always thing it's important to have a good physical understanding of the system in question before using BioSimSpace. That way you can look at the mappings in order to validate that they are reasonable and catch errors before submitting jobs. As @maxkuhn suggested, it might be more robust to propose pathways that go through intermediates in order to minimise the size of the perturbations. This is something that has to be done manually at present, although BioSimSpace might be able to propose suggestions in future. (We are also planning on wrapping functionality from [Lomap](https://github.com/MobleyLab/Lomap).

**Comment by lohedges** [comment] 2019-08-06 14:50
In relation to [this](#102) issue, I've updated the code so that our own internal MCS code is used as a fallback whenever RDKit fails to generate a mapping that includes the pre-match. This seems to work well and I can now recover all of the problem mappings that are identified in your notebook, bar the following two pairs:

```
CAT-17i_CAT-13f
CAT-4m_CAT-4c
```

For the first pair: I think the pre-match that you propose is inverted, since you use exactly the same mapping several times above that point in the notebook where `CAT-17i` is the second ligand, rather than the first. If I invert the pre-match (or swap the order of the molecules) then I do recover a decent mapping.

Could you check the pre-match for the second pair? Perhaps there is a typo, or something unphysical about it. I've tried increasing the timeout significantly but it still doesn't return a mapping (just the pre-match.) I also tried inverting it (just in case), but no luck there either.

Cheers.

**Comment by dlukauskis** [comment] 2019-08-07 15:36
Yep, I get good matches now. 

`CAT-17i_CAT-13f` was my mistake, a lesson not to blindly copy-paste!

`CAT-4m_CAT-4c` works just fine as well with just a single pre-match. [Here](https://github.com/michellab/BioSimSpace/files/3477769/4m_4c.zip) is a folder with the merged molecule + mapping.

BSS.__version__ == 2019.1.0+251.g22d2a52

**Comment by lohedges** [comment] 2019-08-07 15:39
Cracking, thanks for the update. Feel free to close the issue when you are happy. If you find further mapping issues you can re-open the thread, or post a new topic.

Cheers.

**Comment by dlukauskis** [comment] 2019-08-09 14:19
I've ran into issues concerning other systems from the Schrodinger test set.

1. One of the p38 pairs, 3fly_2x, fail to merge, despite prematching all the atoms or giving it a perfect mapping. [Here](https://github.com/michellab/BioSimSpace/files/3486711/p38_issue.zip) is the folder with inputs.

2. Two pairs in MCL1, 30_38, 32_46, produced some strange Sire errors during right before somd-freenrg simulations started, mentioning missing atoms. I thing merge failed to make some dummies for the perturbation.  [Attaching](https://github.com/michellab/BioSimSpace/files/3486725/MCL1_problem_pairs.zip) the error trace and the merged ligands.

**Comment by lohedges** [comment] 2019-08-09 19:34
The second one is caused by missing atom name records for some of the bond parameters in the pert file. This looks like it was caused by a copy/paste error when I switched to allowing a variable number of bonds in the two end states.

Still working on the first issue.

**Comment by lohedges** [comment] 2019-08-12 14:41
The problem is the atoms `O32` and `H39` labeled in the following image:

![vmdscene](https://user-images.githubusercontent.com/648557/62872313-1cffcd80-bd15-11e9-9752-21a4895fac21.png)

These go from being connected through a dihedral, to being unbonded. Looking at the picture, I'm not sure if this should be classified as a ring-breaking or growing event. I'll have a think to see how the ring detection logic can be updated to capture this.

**Comment by lohedges** [comment] 2019-10-16 14:35
Closing as the source of the problem is known. (See issue referenced above.)

**Closed by lohedges** 2019-10-16 14:35 UTC
Labels: bug
