### ISSUE TITLE
PrepareFEP fails to transfer improper parameters between states

### ISSUE THREAD

**Issue by halx** [michellab/BioSimSpace#254] opened 2021-12-08 10:10 UTC
@jmichel80 The script PrepareFEP fails to transfer the impropers between the states, see example files in the attachment.  Input2 defines impropers for the amide group which should appear as the final parameters for state1 (which has the amide transformed to sulfonamide so no impropers needed).  The barrier heights are clearly wrong as they should be 10.5 and 1.1 respectively.  In the backward case the parameters look correct but the keyword "final_form" is malformed and has the underscore replaced with a space.  Sire silently ignores this error.

prepareFEP.py --input1 Input1.parm7 Input1.rst7 --input2 Input2.parm7 Input2.rst7 --output test --mapping mapping.txt

[PrepareFEP_failure.zip](https://github.com/michellab/BioSimSpace/files/7675161/PrepareFEP_failure.zip)

**Comment by lohedges** [comment] 2021-12-08 10:17
Thanks, @halx. I'll try to take a look at this later today. Could you please confirm which version of BioSImSpace you are using, e.g. latest devel, or a tagged release, conda package, etc?

**Comment by halx** [comment] 2021-12-08 10:21
commit 956ece1ecabcb09b793d7e4c833b2b63426c2f6b

**Comment by lohedges** [comment] 2021-12-08 10:24
Thanks for clarifying. I've fixed the missing underscores. Just try to figure out what's wrong with the impropers, since the logic looks the same as for all other terms.

**Comment by lohedges** [comment] 2021-12-08 10:53
Hi @halx, I think I've found and fixed the issue. Could you test at your end and let me know if this resolves the problem? Note that I've also needed to update the [prepareFEP.py](https://github.com/michellab/BioSimSpace/blob/devel/nodes/playground/prepareFEP.py) script to pass through the `bond` property name to the `saveMolecules` function so that a `CONECT` record can be written. This might not be needed depending on what version of the code you are using.

**Comment by jmichel80** [comment] 2021-12-08 12:21
Hi @lohedges could you elaborate on why this happened and this systematically applied to all input generated by prepareFEP.py ? 
Should the SireIO::perturbationslibrary parser code be updated to avoid future silent failures when reading malformed input ? (https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireIO/perturbationslibrary.cpp)

**Comment by lohedges** [comment] 2021-12-08 12:28
Hi @jmichel80. This was simply a typo in the pert file writer, nothing else. While there are unit tests to make sure that the merged topology is valid, there aren't currently any that compare the expected output of pert files. You did this manually when the code was first written, e.g. by comparing against existing output of FESetup, but this was never formalised. (There are multiple input files where you compared output while we ironed out issues.) This would be made (somewhat) easier if / when I have time to add a pert file reader, since we can validate that the round-trip process is symmetric. I can only assume that the bug was never caught by yourself / Toni since the test ligands didn't have any improper terms, or the perturbation was only applied in one direction, where the missing underscore might not have been spotted.

I agree that a formatting error in the pert file _should_ trigger an error. I'll take a look at how this is parsed to see how such errors can be caught. The same thing applies to SOMD too, since any mistyped input in the config file will just fall back on using the default value, even when that isn't desired.

**Comment by lohedges** [comment] 2021-12-08 12:37
Looking at the Sire code it looks like there is no check that there is a matching `final_form` for each `initial_form` record. (Or even checks for the presence of other terms too.) It only checks that the start and end records exists, so what's in between could be nonsense.

**Comment by lohedges** [comment] 2021-12-08 14:59
I've now added a file comparison unit test using the perturbation file generated by this ligand pair as input. We'd obviously need to adjust this following any formatting tweaks, but it will serve as a useful regression test for now.

**Comment by halx** [comment] 2021-12-09 08:33
Fix looks fine to me.  A stringent test would require you to both check pert **and** parm7 files because the pert file only lists the differences.  So you need to check that the pert file really picks up on all changing parameters from the two parm7 files.

**Comment by lohedges** [comment] 2021-12-09 10:10
Thanks for confirming. I agree with what you say regarding the test, but as things currently stand the code used to detect differences in the parm7 files (actually between any compatible topologies from whatever files) _is_ the code used to generate the pert file, i.e. the two things are coupled and an error in one would lead to an error in the other, but wouldn't be detected. What we really need is a pert file writer and a way to fully reconstruct the merged topology from the pert file and the lambda = 0 prm7/rst7 files. That way we can do a _full_ self-consistency check. We can already do this for the GROMACS FEP topology and are also able to write individual lamba = 0 and lamba = 1 end states to AMBER format files, then load them back to recover the merged topology, i.e. using [BioSimSpace.IO.savePerturbableSystem](https://biosimspace.org/api/generated/BioSimSpace.IO.savePerturbableSystem.html#BioSimSpace.IO.savePerturbableSystem) and [BioSimSpace.IO.readPerturbableSystem](https://biosimspace.org/api/generated/BioSimSpace.IO.savePerturbableSystem.html#BioSimSpace.IO.readPerturbableSystem ).We also have fairly extensive tests for our merging code to make sure that the energies of the extracted end states agree with those of the original molecules.

Just a note on the scope of this bug:

- Impropers that were unique to the lambda = 1 state would have the wrong terms in the potential, e.g. barrier height. The value would be taken from those of the last dihedral shared between the end states (dihedral for same atoms, but with different terms).
- The missing underscore was present in both the dihedral _and_ improper section, but only for records unique to the lambda = 0 states in both cases, i.e. atoms in the lambda = 0 state are involved in a dihedral, but aren't at lambda = 1. The reverse situation was fine, i.e. dihedrals/impropers unique to lambda = 1, as well as for shared impropers/dihedrals. Looking at the [Sire code](https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireIO/perturbationslibrary.cpp) that reads the pert file, it appears that a missing `final_form` record will mean that the lambda = 1 state terms would have been set to null, i.e. zero. The Sire code has a check that the number of parameters for an improper is 3, but this uses modulo arithmetic so would also be valid for zero parameters, i.e 0%3 == 0:

```cpp
if ( ( final_params.size() % 3 ) != 0)
{
    throw SireError::program_bug( QObject::tr(
           "Non standard number of parameters in perturbation for improper. Should be a multiple of 3")
           , CODELOC );
}
```

(The same is true for the logic used in checks for all other potential terms, i.e.. bonds, angles, and dihedrals.)

I'm actually surprised that the code doesn't crash, since following the above check it will continue to loop over a list with zero entries. (The `final_form` list is cleared for each new dihedral/improper.) When I get a moment I'll add some debug statements to see if I can figure out what it actually uses for the parameters in this case.

I'll close this for now since it seems that the original issue has been resolved. Please feel free to re-open, or start another thread, if you come across further issues.

Thanks again for catching this. It is much appreciated.

**Closed by lohedges** 2021-12-09 10:10 UTC
Labels: bug

**Comment by lohedges** [comment] 2021-12-09 15:17
@kexul, @msuruzhon, @annamherz: Just tagging so that you are aware of this bug. You might want to pull in changes, or update to the latest conda version so that you can check the implications of this with some existing input data.

Cheers.

**Comment by msuruzhon** [comment] 2021-12-09 17:10
@lohedges thanks for that. Just to make sure I am on the same page, does this bug only apply to output files used for SOMD? Are the merged molecule objects affected? What about saving/reading a serialised object, is that an issue? Cheers.

**Comment by lohedges** [comment] 2021-12-09 17:33
> ...does this bug only apply to output files used for SOMD?

Yes, that's right, the bug only affects the specific perturbation input file (pert file) used for SOMD. The merged molecule objects themselves are unaffected, there was just a mistake in translating this information into the perturbation file format. (For the specific terms mentioned above.) Saving / reading a serialised object is also unaffected.

Cheers.

**Comment by jmichel80** [comment] 2021-12-09 17:38
The bug would apply to perturbations that involve changes in improper parameters. Typically that means change of hybridisation for certain carbons. That’s not the most common FEP use case so may not be picked by ‘simple’ perturbations

**Comment by kexul** [comment] 2021-12-10 04:07
Thanks for the information 🤗, will update soon!
