### ISSUE TITLE
Box too small for the free leg

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#111] opened 2019-08-12 12:13 UTC
If I equilibrate a system for FEP and then try to setup the folder tree, some ligand pairs complain that the box size for the free leg is too small, even when specifying > 45 angstrom. [Attaching](https://github.com/michellab/BioSimSpace/files/3492220/box_error.zip) an equilibrated system with a notebook. @lohedges can you replicate the error with my inputs? Ran on BSS.__version__ == 2019.1.0+294.g7aca325

**Comment by lohedges** [comment] 2019-08-12 12:27
Looking at the error from `gmx grommp` the `box_test` directory:

```
ERROR 1 [file solvated.top, line 546]:
  virtual site H2 (Res LIG-1) has non-zero mass 1.008 (state A) / 1.008
  (state B)
       Check your topology.



ERROR 2 [file solvated.top, line 546]:
  virtual site H3 (Res LIG-1) has non-zero mass 1.008 (state A) / 1.008
  (state B)
       Check your topology.
```

It looks like dummy atoms in the topology have non-zero mass.

I think your problem is here:

```python
equilibrated = BSS.Process.Somd(solvated, protocol=custom_somd_equilibration,platform="CUDA", work_dir=job_dir) \
                  .start().getSystem(block=True)
new_system = BSS.IO.readMolecules(['latest.rst','somd.prm7'])
molecule = new_system[0]
print(molecule)
free_leg = BSS.Solvent.tip3p(molecule=molecule, box=3*[60*BSS.Units.Length.angstrom],work_dir='box_test')
```

Rather than using the equilibrated system returned by the `getSystem` method of the process (which simply copies back the updated coordinates of the system, thus preserving the merged molecule properties that are required for solvation and the free energy simulation) you appear to be reading the SOMD output files directly.

Is there a reason that you are using `new_system` rather than `equilibrated`?

**Comment by dlukauskis** [comment] 2019-08-12 12:47
I have done that, running the entire protocol in a script that indeed uses `.getSystem()`. I've made the notebook to best replicate the error I'm getting. The actual error trace I got was:

```
Traceback (most recent call last):
  File "somd_binding_freenrg.py", line 95, in <module>
    engine='SOMD', box=3*[50*BSS.Units.Length.angstrom])
  File "/home/e620070/anaconda3/envs/latest_BSS/lib/python3.7/site-packages/BioSimSpace/FreeEnergy/_binding.py", line 123, in __init__
    self._system1 = _Solvent.solvate(water_model, molecule=molecule, box=box)
  File "/home/e620070/anaconda3/envs/latest_BSS/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py", line 104, in solvate
    return _model_dict[model](molecule, box, shell, ion_conc, is_neutral, work_dir, property_map)
  File "/home/e620070/anaconda3/envs/latest_BSS/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py", line 258, in tip3p
    _validate_input(molecule, box, shell, ion_conc, is_neutral, work_dir, property_map)
  File "/home/e620070/anaconda3/envs/latest_BSS/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py", line 501, in _validate_input
    raise ValueError("The 'box' is not large enough to hold the 'molecule'")
ValueError: The 'box' is not large enough to hold the 'molecule'
```
Using [this](https://github.com/michellab/BioSimSpace/files/3492392/somd_binding_freenrg.txt) script.

**Comment by lohedges** [comment] 2019-08-12 13:51
I have tried reproducing the error using the suggested input from your notebook (I note that you don't include the crystal water file) and I don't trigger the error.

Using the protein and a merged molecule comprised of the `CAT-24` and `CAT-17e` I can solvated using the box size returned by the `getAxisAlignedBoundingBox` method, i.e.:

```python
system = protein + merged
box_min, box_max = system.getAxisAlignedBoundingBox()
box_size = [y - x for x, y in zip(box_min,box_max)]
print(box_size)
[60.0880 A, 62.3040 A, 54.7660 A]
```

(Note that this is the minimum size. You really should really include a buffer too.)

I can then happily solvate the system using this box:

```python
solvated = BSS.Solvent.tip3p(molecule=system, box=box_size)
print(solvated)
<BioSimSpace.System: nMolecules=4644>
```

I can also generate the binding free energy. (This box is used for both legs):

```python
protocol = BSS.Protocol.FreeEnergy()
free_nrg = BSS.FreeEnergy.Binding(solvated, protocol)
```

Let's try to use a smaller box for the free leg. We'll compute this from the merged molecule:

```python
box_min, box_max = merged.getAxisAlignedBoundingBox()
box_size = [y - x for x, y in zip(box_min,box_max)]
print(box_size)
[6.0170 A, 13.1440 A, 8.6680 A]
```

Now let's try to initialise the free energy object:

```python
free_nrg = BSS.FreeEnergy.Binding(solvated, protocol, box=box_size)
```

This gives the same error that you are seeing:

```
RuntimeError: 'gmx grommp' failed to generate output! Perhaps your box is too small?
```

This is because we are choosing to neutralise the solvated system and `gmx genion` needs a minimum box size to be able to perform its calculation. Let's increase the box a bit, e.g.:

```python
box_size = [x + 5*BSS.Units.Length.angstrom for x in box_size]
free_nrg = BSS.FreeEnergy.Binding(solvated, protocol, box=box_size)
```

```
RuntimeError: 'gmx grommp' failed to generate output! Perhaps your box is too small?
```

Argh, still to small. Let's iterate until the box is big enough. This worked for me:

```
print(box_size)
[26.0170 A, 33.1440 A, 28.6680 A]
```

So, about 30 Angstom cubed is the minimum for this merged molecule. I'm not sure why a 50 Angstrom box isn't working for you, unless we're not looking at the same system. Perhaps your version of GROMACS is different, which could mean that `gmx grommp` or `gmx genion` has changed.

**Comment by jmichel80** [comment] 2019-08-13 07:54
Can we change this to use an 'extent' approach to extend the minimum bounding box by a certain range as done in with e.g. in https://github.com/michellab/BioSimSpace/blob/devel/nodes/playground/solvate.py

```
system = BSS.Solvent.solvate(node.getInput("water"), molecule=system,
                                                     shell=node.getInput("extent"),
                                                     ion_conc=node.getInput("ion_conc"))
```

**Closed** 2019-08-22 10:24 UTC
Labels: bug

**Comment by bcossins** [comment] 2020-12-20 22:06
@lohedges @jmichel80 just been testing the solvate.py node and having trouble with the shell part of it. Is it worth adopting the solution suggested by Lester here and integrating it into the solvate function and node?

**Comment by jmichel80** [comment] 2020-12-21 08:27
Hi @bcossins can you post more details, can you make it work by using a larger box?

**Comment by bcossins** [comment] 2020-12-22 10:32
Hey @jmichel80, yea sorry. I was using a large protein system with a a cubic box of ~110 Angtsroms. I cannot share this case but if you really need it can try and generate a version I can share. The error message with the standard script is as follows: -

[u046906@slhlnxws048 solvate]$ python solvate_old.py --input structure.prm7 structure.rst7 --extent 12 --ion_conc 0.15 --output solvated2

=======================================================
Respecting your privacy - not sending usage statistics.
Please see http://siremol.org/analytics for more information.
=======================================================

Traceback (most recent call last):
  File "solvate_old.py", line 74, in <module>
    ion_conc=node.getInput("ion_conc"))
  File "/home/model/MD-SOFTWARE/miniconda3-BSS/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py", line 116, in solvate
    return _model_dict[model](molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
  File "/home/model/MD-SOFTWARE/miniconda3-BSS/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py", line 287, in tip3p
    is_neutral, work_dir=work_dir, property_map=property_map)
  File "/home/model/MD-SOFTWARE/miniconda3-BSS/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py", line 667, in _solvate
    command += " -shell %f" % shell.nanometers().magnitude()
UnboundLocalError: local variable 'command' referenced before assignment

Replacing the with the following snippet works fine: -

# Smart bit of code that picks the dimensions of the box, adding 10A buffer 
box_min, box_max = system.getAxisAlignedBoundingBox()
box_size = [y - x for x, y in zip(box_min,box_max)]
box_size = [x + 10*BSS.Units.Length.angstrom for x in box_size]
system = BSS.Solvent.solvate(node.getInput("water"), molecule=system,
                                                     box=3*[max(box_size)],
                                                     ion_conc=node.getInput("ion_conc"))
#system = BSS.Solvent.solvate(node.getInput("water"), molecule=system,
#                                                     shell=node.getInput("extent"),
#                                                     ion_conc=node.getInput("ion_conc"))

**Comment by jmichel80** [comment] 2020-12-22 14:52
I think new code in the library may have broken the old solvated.py script. For the avoidance of doubt if you could post the exact script you are using now (without inputs) @lohedges and I can take a look in January.

**Comment by lohedges** [comment] 2020-12-28 10:43
Yes, it looks like something has got missed when I added support for solvation with triclinic boxes. Should be an easy fix when I'm back.

Cheers.

**Comment by lohedges** [comment] 2021-01-05 13:34
This should now be fixed. An updated Conda package is currently being built and will be available soon.
