### ISSUE TITLE
Align Module Issues

### ISSUE THREAD

**Issue by miroslav351** [michellab/BioSimSpace#39] opened 2018-10-26 11:59 UTC
Hello,

I have been trying to use BioSimSpace for the past several days to obtain good ligand-ligand mapping and merging and I have run into several issues in the Align module:

1.  When calling matchAtoms(), I run into the following error:
**AttributeError: 'Evaluator' object has no attribute 'findMCSmatches'**
However, when I try to manually call findMCS() instead, the molecules are aligned, but the alignment    is much worse than it should be, even if one of the molecules is practically a substructure of the other one (note that I run into the same problem using RDkit with ConstrainedEmbed())

2. After alignment, manual creation of a merged structure using merge() (and the mapping obtained by manually calling findMCS()) results in a molecule which has no atoms and results in a blank screen when one tries do visualise it. Additionally, saving this to a mol2 file results in a file full of dummy atoms with coordinates of 0, 0, 0. Perhaps not surprisingly, attempting to save this object to an AMBER format fails as well. (the original molecules have already been parametrised in AMBER so the parameters should be loaded)

Note that I am running the latest commits of both BioSimSpace(2018.1.1+385.g077abfd) and Sire (2018.2.0) on a MacOS High Sierra build.

Best wishes,
Miroslav

**Comment by lohedges** [comment] 2018-10-26 12:13
Hi Miroslav,

You'll need to use the `feature-mapping` branch of Sire to be able to use the latest functionality from `BioSimSpace.Align`. I've made modifications to the MCS matching algorithm to allow it to return the complete set of matches, rather than the most recent one. There are also modifications to support matching of hydrogen atoms, and matches between hydrogens and heavy atoms. Currently, the most up-to-date branch of BioSimSpace is `feature-freenrg`, so I'd suggest testing with that.

For your second question: You currently can't write the merged molecule to all formats as the parsers do not know how to interpret it. (The only one is Gromacs.) If you just want to visualise things, say in VMD, you can do the following:

```python
# Assumes you have a merged molecule called "mol".

# Create a property map.
prop_map = {}

# Here we map all molecular properties to those from the lambda = 0 state,
# e.g. "coordinates" --> "coordinates0".
for prop in mol._sire_molecule.propertyKeys():
    if prop[-1] == "0":
        prop_map[prop[:-1]] = prop

# Now save the molecule using the mapped properties.
BSS.IO.saveMolecules("merged", mol, "pdb", property_map=prop_map)
```

Hope this helps.

**Comment by miroslav351** [comment] 2018-10-29 13:55
Hi Lester,

Thanks for the reply. These branches did work out for me in the end (although the alignment is not perfect but better than before). The output to gro / top files is also a very useful functionality!

Now I seem to be having issues with solvate(), which is supposed to neutralise the whole system but still leaves total net charge (I think it is ignoring my perturbed ligand which has the same non-neutral charge for both states). But I think this might be a problem of genion, rather than BioSimSpace. I might try to look into it and I will report back if I find something interesting (solvate() takes a long time for a protein - between 5 and 10 mins so testing is a bit difficult).

Many thanks.

**Comment by lohedges** [comment] 2018-10-29 14:14
Thanks for the update. BioSimSpace only performs an alignment using rigid body translations and rotations. If you want to flexibly align one molecule to the other, you could try using [fkcombu](http://strcomp.protein.osaka-u.ac.jp/kcombu/doc/README_fkcombu.html).

BioSimSpace should neutralise the system by default. It's possible that there's any issue with the perturbed ligand, or maybe a molecule with a fractional charge (if you didn't use BioSimSpace to parameterise it). This is definitely something that _should_ work, so I'm happy to take a look if you zip up your input files and an example script and post them here.

If you've not already spotted, you can see the intermediate output files of the solvation by passing a `work_dir` keyword argument to any of the functions, e.g.

```python
solvated = BSS.Solvent.tip3p(molecule=molecule, box=3*[10*BSS.Units.Length.angstrom], work_dir="tmp")
```

**Comment by miroslav351** [comment] 2018-10-29 14:54
Yes, I figured that might be the case, thanks for the suggestion, I might try fkcombu (their server is dead though, I hope it is temporary).

So I wrote a simplified script and tested it again (you never know...) and it still gives a net charge. This time I have redirected all of the output files and I am uploading them as well, because running it takes some time but you are welcome to run the script yourself:
[Input.zip](https://github.com/michellab/BioSimSpace/files/2525729/Input.zip)

All input files have been prepared outside of BioSimSpace using ambertools and converted with a combination of openbabel and parmed so there shouldn't be any issues with that.

**Comment by lohedges** [comment] 2018-10-29 15:10
I believe the issue is because the `-neutral` option doesn't seem to work properly in `genion`. It's supposed to neutralise the system by adding additional ions above those specified by the `-np/-nn` and `-conc` options, but doesn't seem to do this in practice. I've worked around the issue for the case where the user doesn't set a concentration (by just using `-np/-nn`), but haven't fixed things when they do.

**Comment by lohedges** [comment] 2018-11-05 11:11
If you get a chance, could you possible try this again using the latest commit on `feature-mapping`. I ran across a similar issue late last week so may have fixed your problem.

**Comment by miroslav351** [comment] 2018-11-11 11:07
Sorry for the late reply, I seem to have completely missed my notifications!

I tried it again, it seems to work fine now. Many thanks!

**Closed** 2018-11-11 11:07 UTC
