### ISSUE TITLE
BioSimSpace.Align cannot recognize user links_file in development branch correctly 

### ISSUE THREAD

**Issue by Birdlet** [michellab/BioSimSpace#268] opened 2022-01-19 06:39 UTC
# Prerequisites

* I am running the latest version (dev Conda package).
* Operating System: Linux (WSL).
* Installation method: conda  `conda update -c conda-forge -c omnia -c michellab/label/dev biosimspace sire`

# Expected Behavior

I have 5 molecules and I want to build a fep alchemical map with a user-defined `links_file` like this:

```
D2 REFLIG
D3 REFLIG
D4 REFLIG
D5 REFLIG
```

but an `OSError` occurred

## Steps to Reproduce

```python
import BioSimSpace as BSS
import glob 
import csv
import numpy as np
import itertools

ligand_files = glob.glob("{}/*.mol2".format("/mnt/c/Users/birdlet/Downloads/ligand"))
links_file = "/mnt/c/Users/birdlet/Downloads/ligand/link_ori.txt"

ligands = []
ligand_names = []

print(ligand_files)
for filepath in ligand_files:
    # append the molecule object to a list.
    ligands.append(BSS.IO.readMolecules(filepath)[0])
    
    # append the molecule name to another list so that we can use the name of each molecule in our workflow.
    ligand_names.append(filepath.split("/")[-1].replace(".mol2",""))

tranformations, lomap_scores = BSS.Align.generateNetwork(ligands, links_file=links_file, plot_network=True, names=ligand_names)
```

## Failure logs

```python
['/mnt/c/Users/birdlet/Downloads/ligand/D2.mol2', '/mnt/c/Users/birdlet/Downloads/ligand/D3.mol2', '/mnt/c/Users/birdlet/Downloads/ligand/D4.mol2', '/mnt/c/Users/birdlet/Downloads/ligand/D5.mol2', '/mnt/c/Users/birdlet/Downloads/ligand/REFLIG.mol2']

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_1058/3479554794.py in <module>
     12     ligand_names.append(filepath.split("/")[-1].replace(".mol2",""))
     13 
---> 14 tranformations, lomap_scores = BSS.Align.generateNetwork(ligands, links_file=links_file, plot_network=True, names=ligand_names)

~/micromamba/envs/biosimspace/lib/python3.7/site-packages/BioSimSpace/Align/_align.py in generateNetwork(molecules, names, work_dir, plot_network, links_file, property_map, n_edges_forced)
    288                                 max3d=3.0,
    289                                 time=3,
--> 290                                 parallel=10)
    291 
    292     # Create the similarity matrices.

~/micromamba/envs/biosimspace/lib/python3.7/site-packages/BioSimSpace/Align/_lomap/dbmol.py in __init__(self, directory, parallel, verbose, time, ecrscore, threed, max3d, output, name, output_no_images, output_no_graph, display, allow_tree, max, cutoff, radial, hub, fast, links_file, known_actives_file, max_dist_from_actives)
    229 
    230         if self.options.links_file and len(self.options.links_file)>0:
--> 231             self.parse_links_file(self.options.links_file)
    232 
    233         if self.options.known_actives_file and len(self.options.known_actives_file)>0:

~/micromamba/envs/biosimspace/lib/python3.7/site-packages/BioSimSpace/Align/_lomap/dbmol.py in parse_links_file(self, links_file)
    408                     logging.info("Added prespecified link for mols",mols,"->",(indexa,indexb),"score",score)
    409         except KeyError as e:
--> 410             raise IOError('Filename within the links file "'+links_file+'" not found: '+str(e)) from None
    411 
    412     def parse_known_actives_file(self, actives_file):

OSError: Filename within the links file "/tmp/tmpufg0eb62/inputs/lomap_links_file.txt" not found: 'D2'
```

## Context

I found this error accured because `BSS.Align.generateNetwork` add a prefix of index to each molecule file  before using lomap, but lomap use user links file which may lack index-prefix or format-postfix. 

https://github.com/michellab/BioSimSpace/blob/38457685dae4861ee360bf1661bdddc37df77e4e/python/BioSimSpace/Align/_align.py#L263-L269

When I rewrite the `links_file` as below, it works:
```
000_D2.mol2 004_REFLIG.mol2
001_D3.mol2 004_REFLIG.mol2
002_D4.mol2 004_REFLIG.mol2
003_D5.mol2 004_REFLIG.mol2
```

Maybe we need some code for dealing with these prefix before lomap, and write some document for users?

**Comment by lohedges** [comment] 2022-01-19 09:59
Thanks for reporting this. I'll tag in @JenkeScheen as he added the support for a user links file. I'm happy to fix myself if needed, but he might have a better solution or workaround.

Cheers.

**Comment by lohedges** [comment] 2022-01-19 10:21
I've just looked at the code at it looks like there are other issues too. For example, the `names` option can be `None`, but it is always used when writing molecules to file. This will need to be fixed too.

**Comment by lohedges** [comment] 2022-01-19 10:40
For example, this part of the code doesn't make sense and would break if `names` isn't specified:

https://github.com/michellab/BioSimSpace/blob/38457685dae4861ee360bf1661bdddc37df77e4e/python/BioSimSpace/Align/_align.py#L477-L499

Here it's using `names` as if it was defined, then sets it in the case that it isn't defined. @JenkeScheen: We'll need to re-think how to uses the `names` list, i.e. it should be defined earlier if unset. The file IO will need to be changed accordingly (this also uses `names`, even when unset) and we'll also need to update the links file written to the working directory to account for the molecule renaming, i.e. the OP's issue.

I can look into this when I get a chance, but you might have a better idea since (I assume) the workflow works for you. (Presumably you are providing correctly formatted `links_file` and `names` options.

Cheers

**Comment by lohedges** [comment] 2022-01-19 10:46
In @Birdlet's case, they are passing in an empty list for the `names` option, so it's unsurprising that this doesn't work. This should be caught though, i.e. if a list, `names` should match the length of the `molecules` list, and we should assert that the names in the `links_file` are actually in the `names` list. We can then update the `links_file` when writing it to disk by using the file name that is written to disk, i.e. the one including the index and file extension.

**Comment by lohedges** [comment] 2022-01-19 10:47
Sorry, they are updating the names in the loop. I'll just flag in the code where I think updates are needed to make the naming consistent.

**Comment by lohedges** [comment] 2022-01-19 11:16
Okay, I think that I've fixed this on my feature branch. If anyone has any input that I could test against, that would be great. Alternatively, @Birdlet you could copy [this](https://github.com/michellab/BioSimSpace/blob/feature_python_tweaks/python/BioSimSpace/Align/_align.py) file into your Python install (overwriting the existing `_align.py` file) to see if things work.

We are currently in the process of creating a new Sire release and updating our CI. As such, a development conda build won't be available until this is complete.

**Comment by JenkeScheen** [comment] 2022-01-19 11:29
Hi, yes I remember coming across this issue before - thanks for reaching out. The way that LOMAP uses the index prefixes is a bit of a hassle, I think the easiest way to deal with the above issue would be to remove the index prefix code from LOMAP altogether (but then again, we'd decided to not touch LOMAP code while we wait for the main developers' update).

@Birdlet just for my understanding, are you including link scores in your `link_file`
```
D2 REFLIG
D3 REFLIG
D4 REFLIG
D5 REFLIG
```
? The point of this code is to be able to pass some score per edge to LOMAP, e.g.:
```
D2 REFLIG 0.3
D3 REFLIG 0.9
D4 REFLIG 0.1
D5 REFLIG 0.4
```
Thanks for the quick fix @lohedges, your fixes seem sensible. I'm not sure I have data to reproduce this issue at the moment but I'd be happy to make some if needed.

**Comment by lohedges** [comment] 2022-01-19 11:32
Thanks, @JenkeScheen. No rush.

The code only requires that each entry in the links_file has two columns. I assume that this is to ensure that this edge is included. Looking at the code, a score is optional. (I guess you can skip the calculation if you have a pre-computed score, or use a more accurate score if it was computed by other means.)

**Comment by JenkeScheen** [comment] 2022-01-19 11:44
You're right, you can see here that the code has been written in such a way that if no third column is present on a line then the line gets set to -2:
https://github.com/michellab/BioSimSpace/blob/1cea711c630424ad782c1fe761c7d717ee99b19c/python/BioSimSpace/Align/_lomap/dbmol.py#L390-L410

which means the edge score is recomputed *but forced to be included* as described in the docs.

**Comment by JenkeScheen** [comment] 2022-01-19 11:46
To be honest I'm not sure what the practical application of this could be as it's much more intuitive to just 1) generate a network and 2) manually add edges that you want to be forced to the list of edges (as provided by LOMAP)

**Comment by lohedges** [comment] 2022-02-01 19:20
Closing as this should be now fixed in devel. Please feel free to re-open if you experience further issues.

**Closed by lohedges** 2022-02-01 19:20 UTC
Labels: bug
