### ISSUE TITLE
Question about intended use of node.validate()

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#62] opened 2019-03-04 15:27 UTC
In the script I uploaded here 

https://github.com/michellab/BioSimSpace/blob/devel/nodes/playground/parameterise.ipynb

the end of the code reads

```
BSS.IO.saveMolecules(node.getInput("output"), molecule, ["prm7", "rst7"])
node.setOutput("nodeoutput", BSS.IO.saveMolecules(node.getInput("output"), molecule, ["prm7", "rst7"]))
node.validate()
```

When run from the command line with e.g.

`~/sire.app/bin/python parameterise.py --input ../protein.pdb/protein-model-01.pdb --output testme --forcefield ff14SB`

The output is

```
-rw-r--r-- 1 julien julien  154 Mar  4 15:21 output.yml
-rw-r--r-- 1 julien julien 222K Mar  4 15:21 testme.prm7
-rw-r--r-- 1 julien julien  18K Mar  4 15:21 testme.rst7
```

Where output.yml was created by the script. 

When run from a notebook the output is

```
-rw-r--r-- 1 julien julien 240K Mar  4 15:24 output.zip
-rw-r--r-- 1 julien julien 222K Mar  4 15:24 testme.prm7
-rw-r--r-- 1 julien julien  18K Mar  4 15:24 testme.rst7

```

Where output.zip was  created by node.validate() but only when executed from the notebook. 

We have already briefly discussed the YAML file, but I would like to clarify when we should use node.validate() or even node.setOutput() . I find it a bit disconcerting that the output of the script depends on the way it was executed.

**Comment by lohedges** [comment] 2019-03-04 17:50
I guess I'm confused what the problem is. You need to always use both
setOutput and validate.

The setOutput function assigns a value to an output requirement specified
near the start of the node. The validate function checks that all output
requirements have been set, that they are valid (match the specified type
and, in the case of files, that they exist), and that no errors were thrown
(work in progress). This should be the last thing in the node.

What is retrurned by validate does depend on the environment, e.g. it
returns a FileLink in Jupyter when users might want to download the output
from a remote server, such as notebook.biosimspace.org. Likewise, the YAML
output is only generated when running non-interactively. However, the
output specified by setOutput is exactly the same regardless of how the
script is run. This is what is interoperable across environments; the other
stuff is just for convenience depending on how it was run.

I could add additional functions, e.g. get FileLink for Jupyter, or getYAML
for the command-line, but it seemed easier to just have validate return it
as necessary.

**Comment by jmichel80** [comment] 2019-03-04 21:09
Ok i get it. 
So we require that if a node is defined, it ends by validating the script. 

What is confusing is that if you run the notebook on your workstation you end up with an uploads folder, the prm7/rst7 files, and also these two files in the file output.zip. It’s not obvious why the script should output twice the same files.

Maybe node.validate() could put all output in a single zip file, and delete all intermediate files if run from a notebook. Might be tricky to implement though.

**Comment by lohedges** [comment] 2019-03-05 08:35
> So we require that if a node is defined, it ends by validating the script.

That's right. It's basically a self-consistency check to ensure that the node does what is intended. If it was part of a larger workflow then it would abort with a clear error message.

> What is confusing is that if you run the notebook on your workstation you end up with an uploads folder, the prm7/rst7 files, and also these two files in the file output.zip. It’s not obvious why the script should output twice the same files.

The prm7/rst7 files (along with any other output) are written to the zip file as a convenient way for the user to download them (using the FileLink). It's true that the files are duplicated on the server, i.e. the individual files are located wherever you wrote them in the script, but it is a pain for the user to navigate back to the Jupyter home page and download them individually.

It's also true that you'll be left with a bit of detritus if you run Jupyter locally. I can't really have the validate method clean up any files, since the user may want to re-run particular cells afterwards and these might fail if the files are deleted. A possible solution is to delete things when the node destructor is called, which would happen when the python interpreter finishes running a script, or when the kernel is stopped/restarted in Jupyter. I'll have a play and see what works.

**Comment by jmichel80** [comment] 2019-03-05 10:16
I think this also applies to the various /tmp/* folders that may have been created during execution of a node ?

**Comment by lohedges** [comment] 2019-03-05 10:25
The directories created with `tempfile.TemporaryDirectory()` are automatically destroyed on exit. The `tempfile` module is smart enough to do this for you.

Having thought about things more, we can't delete stuff in the Node destructor since `__del__` doesn't always work the way you may think, i.e. you can't guarantee that it will be called. We also wouldn't be able to clear any intermediate files that are created by the user but aren't assigned to output variables, since the node doesn't know about them.

As Christopher mentioned, it's probably good to leave files anyway for debugging purposes in case anything goes wrong.

**Closed** 2019-07-31 13:56 UTC
Labels: question
