### ISSUE TITLE
Peturbation files peturb between atom types that should be the same

### ISSUE THREAD

**Issue by mark-cresset** [michellab/BioSimSpace#121] opened 2019-09-19 11:23 UTC
# Expected Behavior

Creating a peturbation file between two molecules; one has a tetrahydropyran and the other a piperidine. Both molecules are otherwise identical, and both have a thiophene elsewhere in their structure.

On parameterising the molecules with teLeap, the carbon atoms in the thiophene are assigned either cc or cd atom types. It appears to be a bit random which atom type is given to which atom: in particular for this pair atoms C4 and C5 are assigned cc/cd in one molecule and cd/cc in the other.

As these atoms are identical in both molecules I would not expect any parameter change for them. 

# Current Behavior

The current behaviour is that peturbation entries are written transforming atom C4 from type cc to type cd, and atom C5 from cd to cc. The LJ parameters are the same, but the bond lengths and angles are not. As a result, there is a parameter change in this part of the molecule despite there being no structural change.

Paolo suggests that changes between supposedly-equivalent AMBER types (cc/cd, ce/cf. etc) be ignored in creating .pert files.
[somd-pert-bug.zip](https://github.com/michellab/BioSimSpace/files/3630930/somd-pert-bug.zip)

## Steps to Reproduce

somd-freenrg.py -C Config.txt

The input files are in the attached tarball.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux Debian stable
* Installation method: Flare

**Comment by lohedges** [comment] 2019-09-19 11:40
I'm not an expert in this, but are the differences in, e.g. bond lengths, between the two ends states a result of the charge distribution of the molecule? (Structurally the substructure of the two end states is the same, but the charge is distributed differently across the whole molecule.) Perhaps @jmichel80 has a better idea about this. I'd be happy to implement the changes proposed by @ptosco if it makes physical sense.

**Comment by lohedges** [comment] 2019-09-19 14:00
Could you upload Mol2/PDB files for the two molecules so that I can run the parameterisation, mapping, and merge myself?

**Comment by jmichel80** [comment] 2019-09-19 14:59
I also need the initial input to dig in, but it sounds like it could be an atom typing perception error from parmchk. Could be because of differences in the initial coordinates of the thiophene ring atoms.

**Comment by lohedges** [comment] 2019-10-16 14:39
Hi @mark-cresset, any update on this? I'd be happy to try to debug if I had access to the original Mol2/PDB files.

**Comment by lohedges** [comment] 2019-10-18 15:14
I've converted the SDF files to PDB and parameterised with GAFF using BioSimSpace but I am unable to merge the molecules based on the mapping that BioSimSpace generates. Are you using LOMAP for your mapping? If so, could you post it here so that I can try to merge with a custom mapping in order to reproduce your output.

**Comment by lohedges** [comment] 2021-06-01 09:26
Closing as the original input files are needed to reproduce, and appear to have been misplaced. Please re-open if you find another example that reproduces the issue.

**Closed by lohedges** 2021-06-01 09:26 UTC
Labels: bug
