### ISSUE TITLE
Possible Merge Bug

### ISSUE THREAD

**Issue by miroslav351** [michellab/BioSimSpace#106] opened 2019-08-07 13:32 UTC
I recently had a very curious case with BioSimSpace not properly merging two molecules, given a correct MCS (until now this hasn't been an issue).

In the attached example, I have two simple molecules that already have the desired final coordinates and only need to be merged topologically. Interestingly, some of the atoms of the end morph occupy the same positions, thereby causing simulations to crash.

I am almost certain that the problem might be atom type mismatch (e.g. I have an atom called C4 on one molecule and an atom called C4 on the other molecule but they are not mapped to one another). Thus, different atoms are confused for the same one and the same positions are output in the GRO file. My question is: is this intended behaviour or not? (I would assume not, but wanted to check regardless)

The files are attached here:
[Files.zip](https://github.com/michellab/BioSimSpace/files/3477206/Files.zip)

Many thanks.

**Comment by lohedges** [comment] 2019-08-07 14:11
Hmm, interesting. What happens if you rename the atom in one of the sets of files? Internally we don't store atoms by name (since this isn't unique) and they can be called whatever you like. I don't think the GROMACS parser uses the name to map anything to the record data.

Perhaps I'm being blind, but could you let me know in which file you are seeing duplicate coordinate entries? (Just paste the lines here if you like.) I see two atoms named `C4` in `lig21.gro87`, but they have different coordinates:

```
    1LIG     C4    9   7.419000   5.890000  11.341000
    1LIG     C4   12   7.364000   5.979000  11.258000
```

We currently don't do anything smart with the positioning of dummy atoms, so it's possible that's what you're seeing, e.g. dummy atoms overlapping with real atoms in one end state.

**Comment by miroslav351** [comment] 2019-08-07 14:26
Interesting, renaming one of the files to unique atom names (not found in the other one) did not change anything in the resulting GRO files...

The relevant lines are:

lig12.gro (big to small):
```
1LIG     C0    4   7.259000   6.014000  11.459000
1LIG     C2   15   7.259000   6.014000  11.459000
```

lig21.gro (small to big):
```
1LIG     C3    7   7.364000   5.979000  11.258000
1LIG     C4   12   7.364000   5.979000  11.258000
```
So this is not a dummy atom positioning issue either, because it is present in both the forward and reverse perturbation (and in any case I would expect the mapper to preserve the original dummy atom position, which is correct).

**Comment by lohedges** [comment] 2019-08-07 14:36
Thanks, that is strange. The `lig12.gro` file should just correspond to the original `ligand1.gro` file, so something has clearly gone wrong. I'll try to track this down.

**Comment by lohedges** [comment] 2019-08-07 15:00
I can confirm that this is a bug with the `Sire.IO.Gro87` parser and is nothing to do with the merge by BioSimSpace. Consider the following:

```python
import BioSImSpace as BSS

# Read the ligand.
lig1 = BSS.IO.readMolecules(["ligand1.top", "ligand1.gro"]).getMolecules()[0]

# Now write it back to file.
BSS.IO.saveMolecules("test", lig1, "gro87")
```

Now compare the files:

`ligand1.gro`
```
GROningen MAchine for Chemical Simulation
   16
    1UNL     C1    1   7.419   5.890  11.341
    1UNL     N1    2   7.359   5.915  11.469
    1UNL     H1    3   7.391   5.867  11.551
    1UNL     C2    4   7.259   6.014  11.459
    1UNL     H2    5   7.205   6.055  11.543
    1UNL     C3    6   7.259   6.055  11.327
    1UNL     H3    7   7.182   6.117  11.280
    1UNL     C4    8   7.364   5.979  11.258
    1UNL     C5    9   7.391   5.996  11.155
    1UNL     H4   10   7.319   6.026  11.078
    1UNL     C6   11   7.497   5.904  11.093
    1UNL     H5   12   7.448   5.824  11.037
    1UNL     C7   13   7.581   5.841  11.205
    1UNL     H6   14   7.637   5.753  11.172
    1UNL     C8   15   7.497   5.817  11.330
    1UNL     H7   16   7.472   5.711  11.335
   5.95100   6.05400   6.18400
```

`test.gro`
```
BioSimSpace System
   16
    1IND     C1    1   7.419000   5.890000  11.341000
    1IND     N1    2   7.359000   5.915000  11.469000
    1IND     H1    3   7.391000   5.867000  11.551000
    1IND     C0    4   7.259000   6.014000  11.459000
    1IND     H2    5   7.205000   6.055000  11.543000
    1IND     C8    6   7.497000   5.817000  11.330000
    1IND     H3    7   7.182000   6.117000  11.280000
    1IND     C6    8   7.497000   5.904000  11.093000
    1IND     C5    9   7.391000   5.996000  11.155000
    1IND    H11   10   7.319000   6.026000  11.078000
    1IND     C4   11   7.364000   5.979000  11.258000
    1IND    H10   12   7.448000   5.824000  11.037000
    1IND     C3   13   7.259000   6.055000  11.327000
    1IND     H9   14   7.637000   5.753000  11.172000
    1IND     C2   15   7.259000   6.014000  11.459000
    1IND     H8   16   7.472000   5.711000  11.335000
   0.00000   0.00000   0.00000
```
The `test.gro` file is the same as what you are seeing. For some reason atoms have been renamed (which shouldn't happen in the Sire parsers), `C0` and `C2` have identical coordinates, and `C7` from the original file is entirely missing.

I'll try and debug the `Gro87` parser.

**Comment by lohedges** [comment] 2019-08-07 15:14
Actually, I think it's that your `ligand1.gro` and `ligand1.top` files have inconsistent information in them (the atom names differ). I would have thought that things would have been matched by index, so this wouldn't be a problem:

`ligand1.gro`
```
GROningen MAchine for Chemical Simulation
   16
    1UNL     C1    1   7.419   5.890  11.341
    1UNL     N1    2   7.359   5.915  11.469
    1UNL     H1    3   7.391   5.867  11.551
    1UNL     C2    4   7.259   6.014  11.459
    1UNL     H2    5   7.205   6.055  11.543
    1UNL     C3    6   7.259   6.055  11.327
    1UNL     H3    7   7.182   6.117  11.280
    1UNL     C4    8   7.364   5.979  11.258
    1UNL     C5    9   7.391   5.996  11.155
    1UNL     H4   10   7.319   6.026  11.078
    1UNL     C6   11   7.497   5.904  11.093
    1UNL     H5   12   7.448   5.824  11.037
    1UNL     C7   13   7.581   5.841  11.205
    1UNL     H6   14   7.637   5.753  11.172
    1UNL     C8   15   7.497   5.817  11.330
    1UNL     H7   16   7.472   5.711  11.335
   5.95100   6.05400   6.18400
```

`ligand1.top`
```
[ atoms ]
;   nr       type  resnr residue  atom   cgnr    charge       mass  typeB    chargeB      massB
; residue    1 IND rtp IND q 0.0
    1         ca      1    IND     C1      1 -0.04720000  12.010000   ; qtot -0.047200
    2         na      1    IND     N1      2 -0.19640000  14.010000   ; qtot -0.243600
    3         hn      1    IND     H1      3 0.29770000   1.008000   ; qtot 0.054100
    4         cd      1    IND     C0      4 -0.10910000  12.010000   ; qtot -0.055000
    5         h4      1    IND     H2      5 0.16300000   1.008000   ; qtot 0.108000
    6         cc      1    IND     C8      6 -0.18720000  12.010000   ; qtot -0.079200
    7         ha      1    IND     H3      7 0.15600000   1.008000   ; qtot 0.076800
    8         ca      1    IND     C6      8 -0.09580000  12.010000   ; qtot -0.019000
    9         ca      1    IND     C5      9 -0.08200000  12.010000   ; qtot -0.101000
   10         ha      1    IND    H11     10 0.13300000   1.008000   ; qtot 0.032000
   11         ca      1    IND     C4     11 -0.15900000  12.010000   ; qtot -0.127000
   12         ha      1    IND    H10     12 0.12800000   1.008000   ; qtot 0.001000
   13         ca      1    IND     C3     13 -0.11300000  12.010000   ; qtot -0.112000
   14         ha      1    IND     H9     14 0.12800000   1.008000   ; qtot 0.016000
   15         ca      1    IND     C2     15 -0.14600000  12.010000   ; qtot -0.130000
   16         ha      1    IND     H8     16 0.13000000   1.008000   ; qtot 0.000000
```

Updating the names in the `top` file so they match those in the `gro` fixes things. (I've assumed the same order, since things should be by index.)

`lig12.gro87`
```
BioSimSpace System
   16
    1LIG     C1    1   7.419000   5.890000  11.341000
    1LIG     N1    2   7.359000   5.915000  11.469000
    1LIG     H1    3   7.391000   5.867000  11.551000
    1LIG     C2    4   7.259000   6.014000  11.459000
    1LIG     H2    5   7.205000   6.055000  11.543000
    1LIG     C3    6   7.259000   6.055000  11.327000
    1LIG     H3    7   7.182000   6.117000  11.280000
    1LIG     C4    8   7.364000   5.979000  11.258000
    1LIG     C5    9   7.391000   5.996000  11.155000
    1LIG     H4   10   7.319000   6.026000  11.078000
    1LIG     C6   11   7.497000   5.904000  11.093000
    1LIG     H5   12   7.448000   5.824000  11.037000
    1LIG     C7   13   7.581000   5.841000  11.205000
    1LIG     H6   14   7.637000   5.753000  11.172000
    1LIG     C8   15   7.497000   5.817000  11.330000
    1LIG     H7   16   7.472000   5.711000  11.335000
   0.00000   0.00000   0.00000
```

There are no duplicates and it matches the `ligand1.gro` file, as expected.

This does raise the point that Sire should be able to catch mismatched `gro` and `top` files, although maybe this is harder than it seems.

**Comment by miroslav351** [comment] 2019-08-07 15:52
Nicely spotted, thanks for that, I still have no idea why these are mismatched in the first place but that's definitely an issue on my end.

Yes, it would be helpful to have some sort of foolproof mechanism to spot these. Even if Sire does not fix them, a warning or even an error can be pretty useful.

**Comment by lohedges** [comment] 2019-08-07 16:12
Closing since issue has moved over to Sire repo, as referenced above.

**Closed by lohedges** 2019-08-07 16:12 UTC

**Comment by lohedges** [comment] 2019-08-08 12:39
I've now fixed the Sire parser so that these files wouldn't have been read in the first place. I'll still need to have a think about how best to pass error information from Sire to the user. (At the moment we just gobble it and return a general error message.)

**Comment by lohedges** [comment] 2019-08-08 12:48
I now catch any error message from the Sire IO parsers that contains the string "Incompatibility" and raise the following exception:

```
OSError: Incompatibility between molecular information in files: ['ligand1.gro', 'ligand1.top']
```

Hopefully this is a little more informative.
